// Copyright 2026 EcoFuture Technology Services LLC and contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// The fields of a resource read from a runtime schema of Bazis (`schema_create/`,
// `schema_update/`): the JSON Schema of the request document, `{data: {type, attributes,
// relationships}}`, generated by Pydantic with its definitions in `$defs`. An attribute has
// `type`, `format`, `enum`, `readOnly` and `nullable` (Bazis adds it); a relationship is
// `{data: <identifier> | [<identifier>] | null}` whose identifier has the related type as
// the default of `type` (the `relation` of the field in the contract).

import type { JsonSchema } from './types.js';

interface FieldBase {
  name: string;
  /** The label of the field, in the language of the backend. */
  title: string;
  required: boolean;
  readOnly: boolean;
  nullable: boolean;
}

export interface AttributeField extends FieldBase {
  kind: 'attribute';
  /** The JSON Schema type (`string`, `integer`, `number`, `boolean`, `object`, `array`). */
  type: string | null;
  /** `date-time`, `date`, `time`, `uuid`, ... */
  format: string | null;
  /** The allowed values (the choices of the model field). */
  enum: readonly unknown[] | null;
  /** The schema of the attribute (`maxLength`, `minimum`, `default`, ...). */
  schema: JsonSchema;
}

export interface RelationField extends FieldBase {
  kind: 'relation';
  /** The JSON:API type of the related resource. */
  relation: string;
  /** A to-many relationship: it is changed through `useRelationship`, not by the form. */
  many: boolean;
}

export type FormField = AttributeField | RelationField;

/** The resource of a runtime schema: its JSON:API type and its fields in schema order. */
export interface ResourceSchema {
  type: string;
  fields: FormField[];
}

type Node = Record<string, unknown>;

const DEFS = '#/$defs/';

function isNode(value: unknown): value is Node {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/** The node with its `$ref` replaced by the definition (the keys next to `$ref` win). */
function resolve(value: unknown, root: JsonSchema): Node {
  let node = isNode(value) ? value : {};
  const seen = new Set<string>();
  while (typeof node.$ref === 'string' && node.$ref.startsWith(DEFS) && !seen.has(node.$ref)) {
    seen.add(node.$ref);
    const { $ref, ...siblings } = node;
    const definition = isNode(root.$defs) ? root.$defs[$ref.slice(DEFS.length)] : undefined;
    node = { ...(isNode(definition) ? definition : {}), ...siblings };
  }
  return node;
}

/** `anyOf: [X, {type: 'null'}]` as X, and whether null is allowed. */
function withoutNull(value: unknown, root: JsonSchema): { node: Node; nullable: boolean } {
  const node = resolve(value, root);
  const { anyOf, ...siblings } = node;
  if (Array.isArray(anyOf)) {
    const members = anyOf.map((member) => resolve(member, root));
    const others = members.filter((member) => member.type !== 'null');
    if (others.length === 1 && others[0]) {
      return { node: { ...others[0], ...siblings }, nullable: others.length < members.length };
    }
  }
  return { node, nullable: false };
}

function stringOr<T>(value: unknown, fallback: T): string | T {
  return typeof value === 'string' ? value : fallback;
}

function properties(value: unknown, root: JsonSchema): { props: Node; required: string[] } {
  const node = resolve(value, root);
  return {
    props: isNode(node.properties) ? node.properties : {},
    required: Array.isArray(node.required) ? node.required.filter((it) => typeof it === 'string') : [],
  };
}

function base(name: string, property: Node, node: Node, nullable: boolean, required: string[]) {
  return {
    name,
    title: stringOr(property.title, name),
    required: required.includes(name),
    readOnly: property.readOnly === true || node.readOnly === true,
    // Bazis states it; otherwise the schema allows null
    nullable: typeof property.nullable === 'boolean' ? property.nullable : nullable,
  };
}

function attribute(name: string, property: Node, root: JsonSchema, required: string[]): AttributeField {
  const { node, nullable } = withoutNull(property, root);
  return {
    ...base(name, property, node, nullable, required),
    kind: 'attribute',
    type: stringOr(node.type, null),
    format: stringOr(node.format, null),
    enum: Array.isArray(node.enum) ? node.enum : null,
    schema: node,
  };
}

function relation(name: string, property: Node, root: JsonSchema, required: string[]): RelationField {
  const outer = withoutNull(property, root);
  const data = withoutNull(properties(outer.node, root).props.data, root);
  const many = data.node.type === 'array';
  const identifier = properties(many ? data.node.items : data.node, root).props;
  return {
    ...base(name, property, outer.node, outer.nullable || data.nullable, required),
    kind: 'relation',
    relation: stringOr(resolve(identifier.type, root).default, ''),
    many,
  };
}

/**
 * The resource object of `data`: the item itself, or the item of a list (`schema_list/`:
 * an array whose `items` are the members of an `anyOf`; the first one). With bazis-permit
 * the first member has every field of the list and each other one the fields of a group of
 * the field permissions of the user: the schema of a list gives the titles and the types of
 * its fields, not which of them the user sees (an item leaves out the fields it hides).
 */
function itemNode(value: unknown, root: JsonSchema): Node {
  const { node } = withoutNull(value, root);
  if (node.type === 'array') return itemNode(node.items, root);
  if (Array.isArray(node.anyOf) && node.anyOf.length > 0) return itemNode(node.anyOf[0], root);
  return node;
}

/**
 * The resource of a runtime schema: of a create or an update (the fields the user may set),
 * of a retrieve or of a list (the fields the user may see, with their titles).
 */
export function resourceSchema(schema: JsonSchema): ResourceSchema {
  const resource = properties(itemNode(properties(schema, schema).props.data, schema), schema).props;
  const attributes = properties(resource.attributes, schema);
  const relationships = properties(resource.relationships, schema);
  return {
    type: stringOr(resolve(resource.type, schema).default, ''),
    fields: [
      ...Object.entries(attributes.props).map(([name, property]) =>
        attribute(name, resolve(property, schema), schema, attributes.required),
      ),
      ...Object.entries(relationships.props).map(([name, property]) =>
        relation(name, resolve(property, schema), schema, relationships.required),
      ),
    ],
  };
}

/**
 * The properties of the JSON Schema of an object as attributes, such as the payload of a
 * transit (`Transit.payload` of `@/bazis/react/statusy`).
 */
export function objectFields(schema: JsonSchema): AttributeField[] {
  const { props, required } = properties(schema, schema);
  return Object.entries(props).map(([name, property]) =>
    attribute(name, resolve(property, schema), schema, required),
  );
}

/** A schema with its `$ref` resolved, keeping the definitions for the nested ones. */
export function standalone(value: unknown, root: JsonSchema): JsonSchema {
  const node = resolve(value, root);
  return root.$defs === undefined ? node : { ...node, $defs: root.$defs };
}

/** `anyOf: [X, {type: 'null'}]`: whether the schema allows null. */
export function allowsNull(value: unknown, root: JsonSchema): boolean {
  const node = resolve(value, root);
  return node.type === 'null' || withoutNull(node, root).nullable;
}
