// Copyright 2026 EcoFuture Technology Services LLC and contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Types read from the `paths` interface generated by openapi-typescript from the OpenAPI
// of a Bazis project. A route set of Bazis is addressed by its path (`/api/v1/app/model/`);
// its endpoints are that path with a suffix (`{item_id}/`, `schema_list/`...).

import type { ErrorObject } from './errors.js';
import type { Filter } from './filter.js';

export type HttpMethod = 'get' | 'post' | 'patch' | 'delete';

/** The operation of the path `P` for the method `M`; `never` if there is none. */
export type OperationOf<Paths, P, M extends HttpMethod> = P extends keyof Paths
  ? Paths[P] extends Record<M, infer Operation>
    ? Operation
    : never
  : never;

/** The paths of the route sets: the paths that have an item path `<path>{item_id}/`. */
export type RouteSetPath<Paths> = {
  [P in keyof Paths & string]: `${P}{item_id}/` extends keyof Paths ? P : never;
}[keyof Paths & string];

/** The route sets whose endpoint `<path><Suffix>` has the method `M`. */
export type RouteSetWith<Paths, Suffix extends string, M extends HttpMethod> = {
  [P in RouteSetPath<Paths>]: [OperationOf<Paths, `${P}${Suffix}`, M>] extends [never]
    ? never
    : P;
}[RouteSetPath<Paths>];

/** The operation of the endpoint `<P><Suffix>` for the method `M`. */
export type EndpointOf<Paths, P extends string, Suffix extends string, M extends HttpMethod> =
  OperationOf<Paths, `${P}${Suffix}`, M>;

type JsonContent<Content> = Content extends { 'application/vnd.api+json': infer Json }
  ? Json
  : Content extends { 'application/json': infer Json }
    ? Json
    : never;

/** The JSON body of the successful (200 or 201) response of an operation. */
export type ResponseOf<Operation> = Operation extends { responses: infer Responses }
  ? Responses[Extract<keyof Responses, 200 | 201 | '200' | '201'>] extends {
      content: infer Content;
    }
    ? JsonContent<Content>
    : never
  : never;

/** The JSON request body of an operation. */
export type BodyOf<Operation> = Operation extends { requestBody: { content: infer Content } }
  ? JsonContent<Content>
  : never;

type QueryOf<Operation> = Operation extends { parameters: { query?: infer Query } }
  ? [NonNullable<Query>] extends [never]
    ? object
    : NonNullable<Query>
  : object;

type FieldsType<Operation> = keyof QueryOf<Operation> extends infer Key
  ? Key extends `fields[${infer Type}]`
    ? Type
    : never
  : never;

type MetaName<Operation> = ResponseOf<Operation> extends { meta?: infer Meta }
  ? keyof NonNullable<Meta> & string
  : string;

/** Options of every request. */
export interface RequestOptions {
  signal?: AbortSignal;
}

/** `fields[<type>]`: the sparse fieldsets, for the resource types the operation accepts. */
export type FieldsOption<Operation> = [FieldsType<Operation>] extends [never]
  ? unknown
  : { fields?: { readonly [Type in FieldsType<Operation>]?: readonly string[] } };

/** `include`: only retrieve, create and update accept it, list does not. */
export type IncludeOption<Operation> = 'include' extends keyof QueryOf<Operation>
  ? { include?: readonly string[] }
  : unknown;

/** `meta`: the meta fields of the response to return (e.g. `pagination`, `for_change`). */
export type MetaOption<Operation> = 'meta' extends keyof QueryOf<Operation>
  ? { meta?: readonly MetaName<Operation>[] }
  : unknown;

/** `page[limit]` and `page[offset]`. */
export interface Page {
  limit?: number;
  offset?: number;
}

/** The query of a list. */
export type ListOptions<Operation> = RequestOptions &
  FieldsOption<Operation> &
  MetaOption<Operation> & {
    filter?: Filter;
    search?: string;
    /** Field names, `-` before a name for the descending order. */
    sort?: readonly string[];
    page?: Page;
  };

/** The query of an operation on one item. */
export type ItemOptions<Operation> = RequestOptions &
  FieldsOption<Operation> &
  IncludeOption<Operation> &
  MetaOption<Operation>;

/** A resource identifier of a relationship. */
export interface ResourceIdentifier {
  type: string;
  id: string;
}

/** The response of the token endpoint of bazis-users. */
export interface TokenResponse {
  access_token: string;
  token_type: string;
}

/** The progress of an upload: the bytes of the body sent, of `total`. */
export interface UploadProgress {
  loaded: number;
  total: number;
}

/** The options of an upload of bazis-uploadable. */
export interface UploadOptions extends RequestOptions {
  /** The name of the file (`name` of the form); the backend takes the name of the file by default. */
  name?: string;
  /** Called while the body is sent. */
  onProgress?: (progress: UploadProgress) => void;
}

/** A login action of bazis-authing (`meta.actions` of its auth endpoint, `actions` of the contract). */
export interface AuthAction {
  /** The service: `password`, `google`... */
  code: string;
  name: string;
  /** `POST` (a body, such as the username and the password) or `GET` (a page of the service, opened in the browser). */
  method: string;
  url: string;
}

/** The user that the auth endpoint of bazis-authing returns, with the session token. */
export interface AuthUser {
  user_id: string | number;
  username: string;
  first_name: string | null;
  last_name: string | null;
  email: string | null;
  /** The session token (a JWT of bazis-users): send it as the bearer token. */
  token: string;
  logout_actions: readonly Readonly<Record<string, unknown>>[] | null;
}

/**
 * The state of an authorization store of bazis-authing: signed in, with the user and the
 * session token; or not, with the store token (never a session token: a request with it is
 * anonymous) and the errors of the logins of the store (`USERNAME_PASSWORD_ERROR`,
 * `GOOGLE_AUTH_ERROR`...).
 */
export type AuthState =
  | { status: 'signed_in'; user: AuthUser }
  | { status: 'signed_out'; store: string; errors: readonly ErrorObject[] };

/**
 * The statuses of a task of bazis-async-background: `created` (registered, not sent to Kafka
 * yet), `pending` (queued), `processing`, then `completed` or `failed`.
 */
export type BackgroundStatus = 'created' | 'pending' | 'processing' | 'completed' | 'failed';

/** The methods of a request that bazis-async-request runs in the background. */
export type BackgroundMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

/**
 * How a request sent with `X-Async-Background` was answered: queued (202 of
 * bazis-async-request with Kafka) with the id of its task, or run at once (no Kafka, or
 * the middleware is not added) with the body of its response (undefined for 204).
 */
export type BackgroundStart = { status: 'queued'; taskId: string } | { status: 'done'; response: unknown };

/**
 * The state of a task of bazis-async-background (its result with `full_response=true`):
 * its status and its response, null until the task sets one. The response of a request
 * of bazis-async-request is the response of the request it replayed (`ReplayedResponse`).
 */
export interface BackgroundResult {
  status: BackgroundStatus;
  response: unknown;
}

/**
 * The response of a request replayed by bazis-async-request, the response of its task: an
 * HTTP error is a `completed` task with its status.
 */
export interface ReplayedResponse {
  task_id: string;
  endpoint: string;
  status: number;
  headers: readonly (readonly [string, string])[];
  response: unknown;
}

