// Copyright 2026 EcoFuture Technology Services LLC and contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// The socket of bazis-ws: one connection per page, opened with the token of the session and
// closed without it (a logout), reconnected with a backoff when it drops. The server sends
// `{"type": "data", "data": <the published JSON, as a string>}` for each message of the
// channels of the session (the channel of the user, or of an anonymous token, and the common
// channel), `{"type": "pong"}` for `{"type": "ping"}` and `{"type": "error", "code"}` when
// the token is refused or the session fails. It accepts the connection before it takes the
// token: the socket is live only once the server answered after the token (the pong of a
// ping sent with it), and the backoff starts again only after a connection that lasted;
// one that the server drops at once (Redis down) keeps backing off. Pub/sub keeps nothing:
// a message published while the page is not subscribed is lost (`useLiveQueries` refetches
// after a reconnect).

import {
  createContext,
  use,
  useCallback,
  useEffect,
  useEffectEvent,
  useMemo,
  useState,
  type ReactNode,
} from 'react';

import { useSessionKey } from '../context.js';
import { notificationOf, type Notification } from './messages.js';

/**
 * `idle`: no socket (no path or no token); `connecting` (also between two attempts, and
 * until the server answered after the token); `open`: the server took the token, the
 * messages of its channels come; `rejected`: the server refused the token (`error`:
 * `expired_token`, `invalid_token`, `user_not_found`), no new attempt until the token
 * changes; `unavailable`: `UNAVAILABLE_AFTER` handshakes failed in a row (no socket at the
 * path, the server is down), no new attempt until the path or the token changes.
 */
export type SocketStatus = 'idle' | 'connecting' | 'open' | 'rejected' | 'unavailable';

/** The first delay before a new attempt to connect, in milliseconds; it doubles up to `RECONNECT_MAX`. */
export const RECONNECT_MIN = 1000;
export const RECONNECT_MAX = 30000;
/** How often the page pings the server: a socket that answered nothing since the last ping is dead. */
export const PING_INTERVAL = 25000;
/** How long a live connection lasts before the backoff starts again from `RECONNECT_MIN`. */
export const STABLE_AFTER = 10000;
/** The handshakes failed in a row after which the socket is `unavailable`. */
export const UNAVAILABLE_AFTER = 5;
/** The notifications kept, the newest first. */
export const NOTIFICATIONS_KEPT = 50;

/** The key of the next notification: unique in the page, whatever provider received it. */
let nextKey = 1;

/** The errors of bazis-ws after which a new attempt with the same token would fail again. */
const REFUSED = new Set(['expired_token', 'invalid_token', 'user_not_found']);

type Listener = (message: unknown) => void;

interface Socket {
  status: SocketStatus;
  /** The code of the error of the server that refused the token. */
  error: string | null;
  listeners: Set<Listener>;
  notifications: readonly Notification[];
  markRead: () => void;
  clear: () => void;
}

const SocketContext = createContext<Socket | null>(null);

export interface SocketProviderProps {
  /**
   * The path of the socket on the origin of the page (`CAPABILITIES.ws.path`; the dev
   * server proxies it), or a `ws://`/`wss://` URL; null for no socket.
   */
  path: string | null;
  /**
   * The token of the session (a JWT of bazis-users with `exp`), or an anonymous token of
   * bazis-ws (16 to 128 characters `A-Z a-z 0-9 _ -`, generated by the client); null for no
   * socket (a logout closes it). It is sent in the first message, never in the URL.
   */
  token: string | null;
  children: ReactNode;
}

/** The URL of the socket: a path on the origin of the page, or a URL. */
export function socketUrl(path: string): string {
  if (/^wss?:\/\//.test(path)) return path;
  const { protocol, host } = window.location;
  return `${protocol === 'https:' ? 'wss:' : 'ws:'}//${host}${path}`;
}

/** The delay before the attempt after `failures` failed ones: doubled each time, with jitter. */
export function reconnectDelay(failures: number): number {
  const delay = Math.min(RECONNECT_MAX, RECONNECT_MIN * 2 ** failures);
  return delay / 2 + (Math.random() * delay) / 2;
}

/** The data of a message of the server: the published JSON, or its text when it is not JSON. */
function parse(data: string): unknown {
  try {
    return JSON.parse(data) as unknown;
  } catch {
    return data;
  }
}

/**
 * Opens the socket of bazis-ws for the hooks below it (`useSocket`, `useChannel`,
 * `useLiveQueries`, `useNotifications`); inside `BazisProvider`. Keeps the notifications
 * received in the session (`{"action": "notification"}`), dropped when the session changes.
 */
export function SocketProvider({ path, token, children }: SocketProviderProps) {
  const session = useSessionKey();
  // the state of the connection to a path with a token; another path or token is connecting
  const target = path !== null && token !== null ? `${path}\n${token}` : null;
  const [connection, setConnection] = useState<{ target: string | null; status: SocketStatus; error: string | null }>({
    target: null,
    status: 'idle',
    error: null,
  });
  const [notifications, setNotifications] = useState<{ session: string; items: readonly Notification[] }>({
    session,
    items: [],
  });
  const [listeners] = useState(() => new Set<Listener>());

  const received = useEffectEvent((message: unknown) => {
    const notification = notificationOf(message, nextKey, new Date());
    if (notification !== null) {
      nextKey += 1;
      setNotifications((current) => ({
        session,
        items: [notification, ...(current.session === session ? current.items : [])].slice(0, NOTIFICATIONS_KEPT),
      }));
    }
    for (const listener of [...listeners]) listener(message);
  });

  useEffect(() => {
    if (path === null || token === null) return;
    const url = socketUrl(path);
    const current = `${path}\n${token}`;
    const update = (status: SocketStatus, error: string | null = null) => {
      setConnection({ target: current, status, error });
    };
    let socket: WebSocket | null = null;
    // the attempts since the last connection that stayed live STABLE_AFTER: the backoff
    let failures = 0;
    // the attempts in a row whose handshake failed (no socket at the path)
    let unopened = 0;
    let retry: ReturnType<typeof setTimeout> | undefined;
    let ping: ReturnType<typeof setInterval> | undefined;
    let stable: ReturnType<typeof setTimeout> | undefined;
    let stopped = false;

    // the socket without its handlers, closed
    const release = (code?: number) => {
      clearInterval(ping);
      clearTimeout(stable);
      if (socket === null) return;
      socket.onopen = socket.onmessage = socket.onclose = socket.onerror = null;
      socket.close(code);
      socket = null;
    };

    // the socket dropped (a failed handshake, a close, no answer, an error of the server): a
    // new attempt after a delay, none after UNAVAILABLE_AFTER handshakes failed in a row
    const reconnect = (opened: boolean) => {
      release();
      if (stopped) return;
      unopened = opened ? 0 : unopened + 1;
      if (unopened >= UNAVAILABLE_AFTER) {
        stopped = true;
        update('unavailable');
        return;
      }
      update('connecting');
      retry = setTimeout(connect, reconnectDelay(failures));
      failures += 1;
    };

    function connect() {
      const opening = new WebSocket(url);
      socket = opening;
      let opened = false;
      let live = false;
      let alive = true;
      const ask = () => {
        alive = false;
        opening.send(JSON.stringify({ type: 'ping' }));
      };
      opening.onopen = () => {
        opened = true;
        // the server answers the ping after it took the token: the first answer proves the
        // session (a refused token is an error before it)
        opening.send(JSON.stringify({ token }));
        ask();
        ping = setInterval(() => {
          if (alive) ask();
          else reconnect(true);
        }, PING_INTERVAL);
      };
      opening.onmessage = (event: MessageEvent) => {
        alive = true;
        if (typeof event.data !== 'string') return;
        const message = parse(event.data) as { type?: unknown; data?: unknown; code?: unknown } | null;
        if (message?.type === 'error') {
          const code = typeof message.code === 'string' ? message.code : 'internal_error';
          if (!REFUSED.has(code)) {
            reconnect(true);
            return;
          }
          // the same token would be refused again
          stopped = true;
          release(1000);
          update('rejected', code);
          return;
        }
        if (!live) {
          live = true;
          update('open');
          // a connection that the server keeps resets the backoff
          stable = setTimeout(() => {
            failures = 0;
          }, STABLE_AFTER);
        }
        if (message?.type === 'data' && typeof message.data === 'string') received(parse(message.data));
      };
      opening.onclose = () => {
        reconnect(opened);
      };
    }

    connect();
    return () => {
      stopped = true;
      clearTimeout(retry);
      release(1000);
    };
  }, [path, token]);

  const status = target === null ? 'idle' : connection.target === target ? connection.status : 'connecting';
  const error = target !== null && connection.target === target ? connection.error : null;
  const items = useMemo(
    () => (notifications.session === session ? notifications.items : []),
    [notifications, session],
  );
  const markRead = useCallback(() => {
    setNotifications((current) => ({
      session: current.session,
      items: current.items.some((it) => !it.read) ? current.items.map((it) => ({ ...it, read: true })) : current.items,
    }));
  }, []);
  const clear = useCallback(() => {
    setNotifications((current) => ({ session: current.session, items: [] }));
  }, []);
  const value = useMemo(
    () => ({ status, error, listeners, notifications: items, markRead, clear }),
    [status, error, listeners, items, markRead, clear],
  );
  return <SocketContext value={value}>{children}</SocketContext>;
}

function useSocketContext(): Socket {
  const socket = use(SocketContext);
  if (socket === null) throw new Error('The hooks of bazis-ws need a <SocketProvider>.');
  return socket;
}

/** The state of the socket: `status` and the `error` of a refused token. */
export function useSocket(): { status: SocketStatus; error: string | null } {
  const { status, error } = useSocketContext();
  return { status, error };
}

/**
 * Calls the handler with every message of the channels of the session: the published JSON
 * parsed (its text when it is not JSON). The latest handler is called; it is not a
 * dependency.
 */
export function useChannel(handler: (message: unknown) => void): void {
  const { listeners } = useSocketContext();
  const onMessage = useEffectEvent(handler);
  useEffect(() => {
    const listener: Listener = (message) => {
      onMessage(message);
    };
    listeners.add(listener);
    return () => {
      listeners.delete(listener);
    };
  }, [listeners]);
}

/**
 * The notifications received in this session, the newest first (at most
 * `NOTIFICATIONS_KEPT`): pub/sub keeps nothing, so those published before the page
 * subscribed are not there. `unread` counts those not marked read by `markRead()`.
 */
export function useNotifications(): {
  items: readonly Notification[];
  unread: number;
  markRead: () => void;
  clear: () => void;
} {
  const { notifications, markRead, clear } = useSocketContext();
  return { items: notifications, unread: notifications.filter((it) => !it.read).length, markRead, clear };
}
