# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
The theme generated from the design (`bazis_front design`): the text of that of the sample
is the fixture of the components (`assets/ui/test/fixtures/theme.ts`; with
`BAZIS_FRONT_WRITE_FIXTURES=1` the test writes it), the CSS variables of the tokens and of
the dark mode, the defaults of a preset, the files and the lock in a frontend, `--check` and
`front.W005`.
"""

import json
import os
import shutil
from io import StringIO
from pathlib import Path

from django.core.management import CommandError, call_command
from django.test import override_settings

import pytest
import yaml

from bazis.contrib.front.checks import check_design
from bazis.contrib.front.spec import design, theme
from bazis.contrib.front.spec.validate import Specs, validate
from bazis.contrib.front.vendor.lock import digest


REPOSITORY = Path(__file__).resolve().parent.parent
SAMPLE_SPEC = REPOSITORY / 'sample' / 'spec'
FIXTURE = REPOSITORY / 'bazis' / 'contrib' / 'front' / 'assets' / 'ui' / 'test' / 'fixtures' / 'theme.ts'
TEMPLATE_CSS = REPOSITORY / 'bazis' / 'contrib' / 'front' / 'assets' / 'template' / 'src' / 'index.css'


@pytest.fixture
def root(tmp_path):
    """
    A product root with the specs of the sample and a frontend made by `init`.
    """
    shutil.copytree(SAMPLE_SPEC, tmp_path / 'spec')
    with override_settings(BASE_DIR=str(tmp_path)):
        call_command('bazis_front', 'init', '--no-node', stdout=StringIO(), stderr=StringIO())
        yield tmp_path


def generate(*args) -> str:
    out = StringIO()
    call_command('bazis_front', 'design', *args, stdout=out, stderr=StringIO())
    return out.getvalue()


def lock_of(root: Path) -> dict:
    return json.loads((root / 'frontend' / 'bazis-front.lock.json').read_text(encoding='utf-8'))


def edit_theme(root: Path, change) -> None:
    path = root / 'spec' / 'design' / 'theme.yaml'
    data = yaml.safe_load(path.read_text(encoding='utf-8'))
    change(data)
    path.write_text(yaml.safe_dump(data, sort_keys=False), encoding='utf-8')


def rendered(root: Path) -> dict[str, str]:
    result = validate(root, ('design',))
    assert not [it for it in result.errors if it.layer == 'design']
    return theme.render(result.specs)


def root_block(css: str, selector: str) -> dict[str, str]:
    """
    The declarations of a block of the CSS, by property.
    """
    body = css.split(f'\n{selector} {{\n', 1)[1].split('\n}', 1)[0]
    return dict(line.strip().rstrip(';').split(': ', 1) for line in body.splitlines())


def test_the_theme_of_the_sample_is_the_fixture_of_the_components():
    text = rendered(REPOSITORY / 'sample')[theme.THEME_TS]
    if os.environ.get('BAZIS_FRONT_WRITE_FIXTURES') == '1':
        FIXTURE.write_text(text, encoding='utf-8', newline='\n')
    assert FIXTURE.read_text(encoding='utf-8') == text


def test_the_settings_of_the_sample():
    text = rendered(REPOSITORY / 'sample')[theme.THEME_TS]
    assert text.startswith('// Generated by `manage.py bazis_front design` from spec/design/')
    assert 'export const THEME: Theme = {' in text
    for line in ('list_card: "split",', 'navigation: "sidebar",', 'in_progress: "info",', 'dark: true,'):
        assert line in text


def test_the_variables_of_the_tokens():
    css = rendered(REPOSITORY / 'sample')[theme.THEME_CSS]
    tokens = json.loads((SAMPLE_SPEC / 'design' / 'tokens.json').read_text(encoding='utf-8'))
    light = root_block(css, ':root')
    dark = root_block(css, '.dark')
    # every token is a variable: `color.x` is `--x`, the others their name with dashes
    assert light['--primary'] == tokens['color']['primary']['$value']
    assert light['--radius'] == tokens['radius']['$value']
    assert light['--font-body'].startswith('ui-sans-serif, system-ui, -apple-system, "Segoe UI"')
    # a reference is the variable of the token, a missing token its default
    assert light['--font-heading'] == 'var(--font-body)'
    assert light['--ring'] == 'var(--primary)'
    # the dark mode overrides what differs, also by the media query of the system
    assert dark['--primary'] == tokens['dark']['color']['primary']['$value']
    assert '--radius' not in dark
    assert '@media (prefers-color-scheme: dark) {\n  :root:not(.light) {' in css
    # the spacing of the density, and the Tailwind theme over the variables
    assert light['--space-cell-y'] == theme.DENSITY['comfortable']['--space-cell-y']
    mapping = root_block(css, '@theme inline')
    assert mapping['--color-primary'] == 'var(--primary)'
    assert mapping['--color-success-soft'] == design.DERIVED['--success-soft']
    assert mapping['--font-sans'] == 'var(--font-body)'


def test_the_template_imports_the_theme():
    css = TEMPLATE_CSS.read_text(encoding='utf-8')
    assert "@import './bazis/generated/theme.css';" in css
    # the colors are those of the tokens: no variable of a color in the template
    assert ':root' not in css and '--primary' not in css


def test_the_defaults_of_a_preset_without_a_design():
    files = theme.render(Specs())
    assert 'preset: "workspace"' in files[theme.THEME_TS]
    starter = design.tokens_of(design.starter('workspace'))
    assert f'  --primary: {starter["color.primary"][1]["$value"]};' in files[theme.THEME_CSS]

    portal = theme.render(Specs(theme={'spec': 'bazis-design/1', 'preset': 'portal', 'density': 'compact'}))
    text = portal[theme.THEME_TS]
    for line in ('forms: "page",', 'list: "cards",', 'navigation: "topbar",', 'density: "compact",'):
        assert line in text
    css = portal[theme.THEME_CSS]
    assert 'font-size: 106.25%' in css
    assert root_block(css, ':root')['--space-cell-y'] == theme.DENSITY['compact']['--space-cell-y']


def test_without_a_dark_mode():
    tokens = design.starter('workspace')
    light = {key: value for key, value in tokens.items() if key != 'dark'}
    files = theme.render(Specs(tokens=light))
    assert '.dark {' not in files[theme.THEME_CSS] and 'prefers-color-scheme' not in files[theme.THEME_CSS]
    assert 'dark: false,' in files[theme.THEME_TS]


def test_a_token_of_the_product_is_a_variable_and_a_color():
    tokens = json.loads((SAMPLE_SPEC / 'design' / 'tokens.json').read_text(encoding='utf-8'))
    tokens['color']['brand'] = {'$type': 'color', '$value': '#123456'}
    tokens['spacing'] = {'gutter': {'$type': 'dimension', '$value': '3rem'}}
    tokens['font']['mono'] = {'$type': 'fontFamily', '$value': ['JetBrains Mono', 'monospace']}
    css = theme.render(Specs(tokens=tokens))[theme.THEME_CSS]
    light = root_block(css, ':root')
    assert light['--brand'] == '#123456'
    assert light['--spacing-gutter'] == '3rem'
    assert light['--font-mono'] == '"JetBrains Mono", monospace'
    assert root_block(css, '@theme inline')['--color-brand'] == 'var(--brand)'


@pytest.mark.django_db
def test_design_writes_the_theme_and_the_lock(root):
    frontend = root / 'frontend'
    files = rendered(root)
    # init generated it
    for path, text in files.items():
        assert (frontend / path).read_text(encoding='utf-8') == text
    lock = lock_of(root)
    assert lock['design'] == {
        'spec': {path: digest((root / path).read_bytes()) for path in theme.DESIGN_FILES},
        'generated': {path: digest(text.encode('utf-8')) for path, text in files.items()},
    }
    out = generate()
    assert 'Generated the theme' in out
    assert lock_of(root) == lock
    assert 'up to date' in generate('--check')
    assert check_design(None) == []


@pytest.mark.django_db
def test_check_finds_a_changed_design_and_an_edited_theme(root):
    frontend = root / 'frontend'
    edit_theme(root, lambda data: data.update(density='compact'))
    with pytest.raises(CommandError) as error:
        generate('--check')
    assert f'The theme of {frontend} is stale: {theme.THEME_CSS}, {theme.THEME_TS}.' in str(error.value)
    assert 'The design changed since it was generated: spec/design/theme.yaml.' in str(error.value)
    [warning] = check_design(None)
    assert warning.id == 'front.W005'

    generate()
    assert 'density: "compact"' in (frontend / theme.THEME_TS).read_text(encoding='utf-8')
    (frontend / theme.THEME_CSS).write_text('/* edited */\n', encoding='utf-8')
    with pytest.raises(CommandError, match=f'Edited after it was generated: {theme.THEME_CSS}'):
        generate('--check')
    # --check writes nothing
    assert (frontend / theme.THEME_CSS).read_text(encoding='utf-8') == '/* edited */\n'


@pytest.mark.django_db
def test_design_needs_a_design_without_errors(root):
    edit_theme(root, lambda data: data.update(preset='admin'))
    out = StringIO()
    with pytest.raises(CommandError, match='The design has 1 errors'):
        call_command('bazis_front', 'design', stdout=out)
    assert 'D002' in out.getvalue()
    # front.W002 reports the issues: the theme is not compared
    assert check_design(None) == []


@pytest.mark.django_db
def test_design_needs_a_frontend(tmp_path):
    with override_settings(BASE_DIR=str(tmp_path)), pytest.raises(CommandError, match='init'):
        generate()
