# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
The end-to-end tests generated from the scenarios (`bazis_front e2e`): the text of those of
the sample is the fixture of the helpers (`assets/playwright/generated/`, type-checked
against them; with `BAZIS_FRONT_WRITE_FIXTURES=1` the test writes it), the files and the
lock in a frontend, the deletion of the tests of a removed scenario, `--check` and
`front.W003`.
"""

import json
import os
import shutil
from io import StringIO
from pathlib import Path

from django.core.management import CommandError, call_command
from django.test import override_settings

import pytest
import yaml

from bazis.contrib.front.checks import check_e2e
from bazis.contrib.front.spec import e2e
from bazis.contrib.front.spec.validate import validate
from bazis.contrib.front.vendor.lock import digest


REPOSITORY = Path(__file__).resolve().parent.parent
SAMPLE_SPEC = REPOSITORY / 'sample' / 'spec'
FIXTURES = REPOSITORY / 'bazis' / 'contrib' / 'front' / 'assets' / 'playwright' / 'generated'

MANAGER = 'e2e/generated/manager-finishes-a-task.spec.ts'
VIEWER = 'e2e/generated/viewer-only-reads.spec.ts'
EMPTY_TITLE = 'e2e/generated/manager-cannot-save-an-empty-title.spec.ts'
ASSIGNS = 'e2e/generated/manager-assigns-a-task.spec.ts'
ATTACHES = 'e2e/generated/manager-attaches-a-brief.spec.ts'
REPORT = 'e2e/generated/manager-cannot-change-the-report.spec.ts'
NOTIFIED = 'e2e/generated/manager-is-notified-of-a-finished-task.spec.ts'


@pytest.fixture
def root(tmp_path):
    """
    A product root with the specs of the sample and a frontend made by `init`.
    """
    shutil.copytree(SAMPLE_SPEC, tmp_path / 'spec')
    with override_settings(BASE_DIR=str(tmp_path)):
        call_command('bazis_front', 'init', '--no-node', stdout=StringIO())
        yield tmp_path


def generate(*args) -> str:
    out = StringIO()
    call_command('bazis_front', 'e2e', *args, stdout=out, stderr=StringIO())
    return out.getvalue()


def lock_of(root: Path) -> dict:
    return json.loads((root / 'frontend' / 'bazis-front.lock.json').read_text(encoding='utf-8'))


def edit_product(root: Path, change) -> None:
    path = root / 'spec' / 'product.yaml'
    data = yaml.safe_load(path.read_text(encoding='utf-8'))
    change(data)
    path.write_text(yaml.safe_dump(data, sort_keys=False), encoding='utf-8')


def rendered(root: Path) -> dict[str, str]:
    result = validate(root)
    assert not result.errors, [it.as_dict() for it in result.errors]
    return e2e.render(result.specs)


def test_the_tests_of_the_sample_are_the_fixture_of_the_helpers():
    files = {path.removeprefix('e2e/generated/'): text for path, text in rendered(REPOSITORY / 'sample').items()}
    if os.environ.get('BAZIS_FRONT_WRITE_FIXTURES') == '1':
        shutil.rmtree(FIXTURES, ignore_errors=True)
        FIXTURES.mkdir()
        for name, text in files.items():
            (FIXTURES / name).write_text(text, encoding='utf-8', newline='\n')
    assert sorted(files) == sorted(it.name for it in FIXTURES.iterdir())
    for name, text in files.items():
        assert (FIXTURES / name).read_text(encoding='utf-8') == text, name


def test_the_text_of_a_scenario():
    text = rendered(REPOSITORY / 'sample')[MANAGER]
    assert text.startswith(
        '// Generated by `manage.py bazis_front e2e` from the scenario `manager-finishes-a-task` '
        'of spec/product.yaml:\n// never edit it, change the specs and generate it again.\n\n'
        "import { test } from '@playwright/test';\n\n"
        "import { loginAs } from '../bazis';\n\n"
        "import { PRODUCT } from './product';\n\n"
        "test('manager-finishes-a-task', async ({ page }) => {\n"
        "  const app = await loginAs(page, PRODUCT, 'manager');\n"
    )
    # a step of the scenario is a step of the test, its title the step in YAML
    assert (
        "  await test.step('fill: {title: Write the report}', async () => {\n"
        "    await app.fill({ title: 'Write the report' });\n"
        '  });\n'
    ) in text
    # the form of `create` leads to its `then`, the card
    assert (
        "  await test.step('submit', async () => {\n"
        '    await app.submit();\n'
        "    await app.expectScreen('task-card');\n"
        '  });\n'
    ) in text
    assert "    await app.transit('finish', { report: 'Done' });\n" in text
    assert text.endswith(
        "    await app.expectStatus('done');\n"
        "    await app.expectFieldReadonly('title');\n"
        '  });\n'
        '});\n'
    )


def test_the_upload_of_a_file_and_the_values_of_a_card():
    text = rendered(REPOSITORY / 'sample')[ATTACHES]
    # the upload starts the edit of the card; its submit stays on the card
    assert (
        "  await test.step('upload: {field: attachment, file: brief.txt}', async () => {\n"
        "    await app.action('edit');\n"
        "    await app.upload('attachment', 'brief.txt');\n"
        '  });\n'
        "  await test.step('submit', async () => {\n"
        '    await app.submit();\n'
        '  });\n'
        "  await test.step('expect: {values: {title: Attach the brief, attachment: brief.txt}}', async () => {\n"
        "    await app.expectValues({ title: 'Attach the brief', attachment: 'brief.txt' });\n"
        '  });\n'
    ) in text


def test_a_notification_is_expected_after_the_other_keys():
    text = rendered(REPOSITORY / 'sample')[NOTIFIED]
    assert text.endswith(
        "  await test.step('expect: {status: done, notification: Notify the assignee}', async () => {\n"
        "    await app.expectStatus('done');\n"
        "    await app.expectNotification('Notify the assignee');\n"
        '  });\n'
        '});\n'
    )


def test_the_steps_follow_the_walk_of_the_scenario(tmp_path):
    shutil.copytree(SAMPLE_SPEC, tmp_path / 'spec')

    def scenario(data):
        data['scenarios'].append({
            'id': 'manager-renames-a-task',
            'role': 'manager',
            'steps': [
                {'open': 'task-list'},
                {'expect': {'rows': 1, 'state': 'loaded'}},
                {'open_item': {'where': {'title': 'It\'s "the" report \\ 1'}}},
                # the edit of the card starts with its first change
                {'fill': {'title': 'Renamed'}},
                {'fill': {'report': ''}},
                {'submit': {}},
                {'expect': {'error': 'title'}},
                {'action': 'delete'},
            ],
        })

    edit_product(tmp_path, scenario)
    text = rendered(tmp_path)['e2e/generated/manager-renames-a-task.spec.ts']
    body = text[text.index('  await test.step'):]
    assert body == (
        "  await test.step('open: task-list', async () => {\n"
        "    await app.open('task-list');\n"
        '  });\n'
        "  await test.step('expect: {rows: 1, state: loaded}', async () => {\n"
        "    await app.expectState('loaded');\n"
        '    await app.expectRows(1);\n'
        '  });\n'
        """  await test.step('open_item: {where: {title: It\\'s "the" report \\\\ 1}}', async () => {\n"""
        """    await app.openItem({ where: { title: 'It\\'s "the" report \\\\ 1' } });\n"""
        "    await app.expectScreen('task-card');\n"
        '  });\n'
        "  await test.step('fill: {title: Renamed}', async () => {\n"
        "    await app.action('edit');\n"
        "    await app.fill({ title: 'Renamed' });\n"
        '  });\n'
        "  await test.step('fill: {report: \\'\\'}', async () => {\n"
        "    await app.fill({ report: '' });\n"
        '  });\n'
        "  await test.step('submit', async () => {\n"
        '    await app.submit();\n'
        '  });\n'
        "  await test.step('expect: {error: title}', async () => {\n"
        "    await app.expectError('title');\n"
        '  });\n'
        # a destroy leads to its `then`
        "  await test.step('action: delete', async () => {\n"
        "    await app.action('delete');\n"
        "    await app.expectScreen('task-list');\n"
        '  });\n'
        '});\n'
    )


def test_a_submit_followed_by_an_error_fails():
    result = validate(REPOSITORY / 'sample')
    steps = [(it.name, it.edit, it.then) for it in result.specs.scenarios['manager-cannot-save-an-empty-title']]
    assert steps == [
        ('open', False, None),
        ('action', False, None),
        ('fill', False, None),
        # the next step expects an error: the form of `create` stays open, no `then`
        ('submit', False, None),
        ('expect', False, None),
        ('fill', False, None),
        ('submit', False, 'task-card'),
        ('expect', False, None),
        # the edit of the card starts with its first change
        ('fill', True, None),
        ('submit', False, None),
        ('expect', False, None),
        # the edit is still open after the failing submit
        ('fill', False, None),
        ('submit', False, None),
        ('transit', False, None),
        ('expect', False, None),
    ]
    text = rendered(REPOSITORY / 'sample')[EMPTY_TITLE]
    assert text.count("await app.action('edit');") == 1
    assert text.count("await app.expectScreen('task-card');") == 2


def test_the_product_module():
    text = rendered(REPOSITORY / 'sample')[e2e.PRODUCT_TS]
    assert '  roles: {\n    manager: {\n      username: "manager",\n    },\n' in text
    assert '    "task-list": {\n      route: "/tasks",\n    },\n' in text
    assert text.endswith('} as const;\n')


@pytest.mark.django_db
def test_e2e_writes_the_tests_and_the_lock(root):
    out = generate()
    frontend = root / 'frontend'
    files = rendered(root)
    assert sorted(files) == [ASSIGNS, ATTACHES, REPORT, EMPTY_TITLE, MANAGER, NOTIFIED, e2e.PRODUCT_TS, VIEWER]
    for path, text in files.items():
        assert (frontend / path).read_text(encoding='utf-8') == text
    assert 'Generated 7 end-to-end tests' in out
    lock = lock_of(root)
    assert lock['e2e'] == {
        'spec': {
            path: digest((root / path).read_bytes())
            for path in ['spec/product.yaml', 'spec/screens/task-card.yaml', 'spec/screens/task-list.yaml']
        },
        'generated': {path: digest(text.encode('utf-8')) for path, text in files.items()},
    }
    # the same specs give the same files
    before = {path: (frontend / path).read_bytes() for path in files}
    generate()
    assert {path: (frontend / path).read_bytes() for path in files} == before
    assert lock_of(root) == lock
    assert 'up to date' in generate('--check')
    assert check_e2e(None) == []


@pytest.mark.django_db
def test_e2e_deletes_the_tests_of_a_removed_scenario(root):
    generate()
    frontend = root / 'frontend'
    # a file of the product in generated/ is not one of the generator
    (frontend / 'e2e' / 'generated' / 'mine.spec.ts').write_text('// mine\n', encoding='utf-8')
    edit_product(root, lambda data: data['scenarios'].pop(1))

    with pytest.raises(CommandError) as error:
        generate('--check')
    assert f'{VIEWER} (of a scenario that no longer exists)' in str(error.value)
    assert 'The specs changed since they were generated: spec/product.yaml.' in str(error.value)
    assert (frontend / VIEWER).is_file()

    out = generate()
    assert f'Deleted {VIEWER}' in out
    assert not (frontend / VIEWER).exists()
    assert (frontend / MANAGER).is_file()
    assert (frontend / 'e2e' / 'generated' / 'mine.spec.ts').is_file()
    assert sorted(lock_of(root)['e2e']['generated']) == [
        ASSIGNS, ATTACHES, REPORT, EMPTY_TITLE, MANAGER, NOTIFIED, e2e.PRODUCT_TS,
    ]
    generate('--check')


@pytest.mark.django_db
def test_e2e_deletes_only_files_of_e2e_generated(root):
    generate()
    frontend = root / 'frontend'
    lock = lock_of(root)
    # a lock edited by hand, or written by something else, lists other files of the frontend
    others = ['src/main.tsx', 'e2e/bazis/index.ts', 'e2e/generated/../../index.html', '../spec/product.yaml']
    lock['e2e']['generated'].update({path: 'sha256:0' for path in others})
    (frontend / 'bazis-front.lock.json').write_text(json.dumps(lock), encoding='utf-8')
    before = {path: (frontend / path).read_bytes() for path in others}

    # they are not stale
    assert 'up to date' in generate('--check')
    assert check_e2e(None) == []
    generate()
    assert {path: (frontend / path).read_bytes() for path in others} == before
    assert sorted(lock_of(root)['e2e']['generated']) == [
        ASSIGNS, ATTACHES, REPORT, EMPTY_TITLE, MANAGER, NOTIFIED, e2e.PRODUCT_TS, VIEWER,
    ]


@pytest.mark.django_db
def test_e2e_needs_the_helpers(root):
    lock = lock_of(root)
    del lock['assets']['playwright']
    (root / 'frontend' / 'bazis-front.lock.json').write_text(json.dumps(lock), encoding='utf-8')
    for args in ((), ('--check',)):
        with pytest.raises(CommandError, match='`manage.py bazis_front add playwright`'):
            generate(*args)
    assert not (root / 'frontend' / 'e2e' / 'generated').exists()


@pytest.mark.django_db
def test_check_finds_the_stale_and_the_edited_tests(root):
    generate()
    frontend = root / 'frontend'
    (frontend / MANAGER).write_text('// edited\n', encoding='utf-8')
    with pytest.raises(CommandError) as error:
        generate('--check')
    assert f'The end-to-end tests of {frontend} are stale: {MANAGER}.' in str(error.value)
    assert f'Edited after they were generated: {MANAGER}.' in str(error.value)
    assert 'The specs changed' not in str(error.value)
    # --check writes nothing
    assert (frontend / MANAGER).read_text(encoding='utf-8') == '// edited\n'
    [warning] = check_e2e(None)
    assert warning.id == 'front.W003' and MANAGER in warning.msg
    # a generated test that was deleted
    (frontend / VIEWER).unlink()
    with pytest.raises(CommandError, match=f'are stale: {MANAGER}, {VIEWER}'):
        generate('--check')

    generate()
    edit_product(root, lambda data: data['scenarios'][0]['steps'][2]['fill'].update(title='Another'))
    with pytest.raises(CommandError, match='spec/product.yaml'):
        generate('--check')
    [warning] = check_e2e(None)
    assert 'The specs changed since they were generated: spec/product.yaml.' in warning.msg


@pytest.mark.django_db
def test_e2e_needs_specs_without_errors(root):
    edit_product(root, lambda data: data['scenarios'][0]['steps'].insert(0, {'submit': {}}))
    out = StringIO()
    with pytest.raises(CommandError, match='The specs have 1 errors'):
        call_command('bazis_front', 'e2e', stdout=out)
    assert 'P022' in out.getvalue()
    assert not (root / 'frontend' / 'e2e' / 'generated').exists()
    assert 'e2e' not in lock_of(root)


@pytest.mark.django_db
def test_the_system_check_skips_specs_with_errors(root):
    # no tests generated yet: nothing to compare
    assert check_e2e(None) == []
    generate()
    (root / 'spec' / 'product.yaml').write_text('spec: [\n', encoding='utf-8')
    # front.W002 reports the issues
    assert check_e2e(None) == []


@pytest.mark.django_db
def test_e2e_needs_a_frontend(tmp_path):
    with override_settings(BASE_DIR=str(tmp_path)), pytest.raises(CommandError, match='init'):
        generate()


@pytest.mark.django_db
def test_the_migrations_of_the_sample_create_its_workflow():
    from django.apps import apps

    from tasks.workflow import ROLES, STATUSES, TRANSITS

    # the data of the product is in its migrations, not in the e2e data command
    assert set(apps.get_model('permit.Role').objects.values_list('slug', flat=True)) == {
        slug for slug, *_ in ROLES
    }
    assert set(apps.get_model('statusy.Status').objects.values_list('id', flat=True)) == {
        pk for pk, _ in STATUSES
    }
    transits = apps.get_model('statusy.Transit').objects.all()
    assert {(it.id, it.model.app_label, it.model.model) for it in transits} == {
        (pk, 'tasks', 'task') for pk, *_ in TRANSITS
    }


@pytest.mark.django_db
def test_the_e2e_data_of_the_sample(monkeypatch):
    from django.apps import apps
    from django.contrib.auth import get_user_model

    from tasks.workflow import TASK

    roles = set(apps.get_model('permit.Role').objects.values_list('pk', flat=True))
    monkeypatch.delenv('E2E_PASSWORD', raising=False)
    with pytest.raises(CommandError, match='E2E_PASSWORD'):
        call_command('e2e_data', stdout=StringIO())
    for password in ('first-password-0', 'second-password-1'):
        monkeypatch.setenv('E2E_PASSWORD', password)
        call_command('e2e_data', stdout=StringIO())
    # a second run keeps the data and sets the password of the test users again
    for username, role in (('manager', 'manager'), ('viewer', 'viewer')):
        user = get_user_model().objects.get(username=username)
        assert user.check_password('second-password-1')
        assert user.role_current.slug == role and list(user.roles.values_list('slug', flat=True)) == [role]
    assert apps.get_model('tasks.Task').objects.filter(title=TASK).count() == 1
    # the roles are those of the migrations
    assert set(apps.get_model('permit.Role').objects.values_list('pk', flat=True)) == roles


@pytest.mark.django_db
def test_the_e2e_data_needs_the_roles_of_the_migrations(monkeypatch):
    from django.apps import apps
    from django.contrib.auth import get_user_model

    apps.get_model('permit.Role').objects.filter(slug='viewer').delete()
    monkeypatch.setenv('E2E_PASSWORD', 'first-password-0')
    with pytest.raises(CommandError, match="role 'viewer' .* does not exist: migrate"):
        call_command('e2e_data', stdout=StringIO())
    # nothing is created, the role is not either
    assert not get_user_model().objects.filter(username__in=['manager', 'viewer']).exists()
    assert not apps.get_model('permit.Role').objects.filter(slug='viewer').exists()
