# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
The end-to-end tests generated from the scenarios (`bazis_front e2e`): the text of those of
the sample is the fixture of the helpers (`assets/playwright/generated/`, type-checked
against them; with `BAZIS_FRONT_WRITE_FIXTURES=1` the test writes it), the files and the
lock in a frontend, the deletion of the tests of a removed scenario, `--check` and
`front.W003`.
"""

import json
import os
import shutil
from io import StringIO
from pathlib import Path

from django.core.management import CommandError, call_command
from django.test import override_settings

import pytest
import yaml

from bazis.contrib.front.checks import check_e2e
from bazis.contrib.front.spec import e2e
from bazis.contrib.front.spec.validate import validate
from bazis.contrib.front.vendor.lock import digest


REPOSITORY = Path(__file__).resolve().parent.parent
SAMPLE_SPEC = REPOSITORY / 'sample' / 'spec'
FIXTURES = REPOSITORY / 'bazis' / 'contrib' / 'front' / 'assets' / 'playwright' / 'generated'

MANAGER = 'e2e/generated/manager-finishes-a-task.spec.ts'
VIEWER = 'e2e/generated/viewer-only-reads.spec.ts'


@pytest.fixture
def root(tmp_path):
    """
    A product root with the specs of the sample and a frontend made by `init`.
    """
    shutil.copytree(SAMPLE_SPEC, tmp_path / 'spec')
    with override_settings(BASE_DIR=str(tmp_path)):
        call_command('bazis_front', 'init', '--no-node', stdout=StringIO())
        yield tmp_path


def generate(*args) -> str:
    out = StringIO()
    call_command('bazis_front', 'e2e', *args, stdout=out, stderr=StringIO())
    return out.getvalue()


def lock_of(root: Path) -> dict:
    return json.loads((root / 'frontend' / 'bazis-front.lock.json').read_text(encoding='utf-8'))


def edit_product(root: Path, change) -> None:
    path = root / 'spec' / 'product.yaml'
    data = yaml.safe_load(path.read_text(encoding='utf-8'))
    change(data)
    path.write_text(yaml.safe_dump(data, sort_keys=False), encoding='utf-8')


def rendered(root: Path) -> dict[str, str]:
    result = validate(root)
    assert not result.errors, [it.as_dict() for it in result.errors]
    return e2e.render(result.specs)


def test_the_tests_of_the_sample_are_the_fixture_of_the_helpers():
    files = {path.removeprefix('e2e/generated/'): text for path, text in rendered(REPOSITORY / 'sample').items()}
    if os.environ.get('BAZIS_FRONT_WRITE_FIXTURES') == '1':
        shutil.rmtree(FIXTURES, ignore_errors=True)
        FIXTURES.mkdir()
        for name, text in files.items():
            (FIXTURES / name).write_text(text, encoding='utf-8', newline='\n')
    assert sorted(files) == sorted(it.name for it in FIXTURES.iterdir())
    for name, text in files.items():
        assert (FIXTURES / name).read_text(encoding='utf-8') == text, name


def test_the_text_of_a_scenario():
    text = rendered(REPOSITORY / 'sample')[MANAGER]
    assert text.startswith(
        '// Generated by `manage.py bazis_front e2e` from the scenario `manager-finishes-a-task` '
        'of spec/product.yaml:\n// never edit it, change the specs and generate it again.\n\n'
        "import { test } from '@playwright/test';\n\n"
        "import { loginAs } from '../bazis';\n\n"
        "import { PRODUCT } from './product';\n\n"
        "test('manager-finishes-a-task', async ({ page }) => {\n"
        "  const app = await loginAs(page, PRODUCT, 'manager');\n"
    )
    # a step of the scenario is a step of the test, its title the step in YAML
    assert (
        "  await test.step('fill: {title: Write the report}', async () => {\n"
        "    await app.fill({ title: 'Write the report' });\n"
        '  });\n'
    ) in text
    # the form of `create` leads to its `then`, the card
    assert (
        "  await test.step('submit', async () => {\n"
        '    await app.submit();\n'
        "    await app.expectScreen('task-card');\n"
        '  });\n'
    ) in text
    assert "    await app.transit('finish', { report: 'Done' });\n" in text
    assert text.endswith(
        "    await app.expectStatus('done');\n"
        "    await app.expectFieldReadonly('title');\n"
        '  });\n'
        '});\n'
    )


def test_the_steps_follow_the_walk_of_the_scenario(tmp_path):
    shutil.copytree(SAMPLE_SPEC, tmp_path / 'spec')

    def scenario(data):
        data['scenarios'].append({
            'id': 'manager-renames-a-task',
            'role': 'manager',
            'steps': [
                {'open': 'task-list'},
                {'expect': {'rows': 1, 'state': 'loaded'}},
                {'open_item': {'where': {'title': 'It\'s "the" report \\ 1'}}},
                # the edit of the card starts with its first change
                {'fill': {'title': 'Renamed'}},
                {'fill': {'report': ''}},
                {'submit': {}},
                {'expect': {'error': 'title'}},
                {'action': 'delete'},
            ],
        })

    edit_product(tmp_path, scenario)
    text = rendered(tmp_path)['e2e/generated/manager-renames-a-task.spec.ts']
    body = text[text.index('  await test.step'):]
    assert body == (
        "  await test.step('open: task-list', async () => {\n"
        "    await app.open('task-list');\n"
        '  });\n'
        "  await test.step('expect: {rows: 1, state: loaded}', async () => {\n"
        "    await app.expectState('loaded');\n"
        '    await app.expectRows(1);\n'
        '  });\n'
        """  await test.step('open_item: {where: {title: It\\'s "the" report \\\\ 1}}', async () => {\n"""
        """    await app.openItem({ where: { title: 'It\\'s "the" report \\\\ 1' } });\n"""
        "    await app.expectScreen('task-card');\n"
        '  });\n'
        "  await test.step('fill: {title: Renamed}', async () => {\n"
        "    await app.action('edit');\n"
        "    await app.fill({ title: 'Renamed' });\n"
        '  });\n'
        "  await test.step('fill: {report: \\'\\'}', async () => {\n"
        "    await app.fill({ report: '' });\n"
        '  });\n'
        "  await test.step('submit', async () => {\n"
        '    await app.submit();\n'
        '  });\n'
        "  await test.step('expect: {error: title}', async () => {\n"
        "    await app.expectError('title');\n"
        '  });\n'
        # a destroy leads to its `then`
        "  await test.step('action: delete', async () => {\n"
        "    await app.action('delete');\n"
        "    await app.expectScreen('task-list');\n"
        '  });\n'
        '});\n'
    )


def test_the_product_module():
    text = rendered(REPOSITORY / 'sample')[e2e.PRODUCT_TS]
    assert '  roles: {\n    manager: {\n      username: "manager",\n    },\n' in text
    assert '    "task-list": {\n      route: "/tasks",\n    },\n' in text
    assert text.endswith('} as const;\n')


@pytest.mark.django_db
def test_e2e_writes_the_tests_and_the_lock(root):
    out = generate()
    frontend = root / 'frontend'
    files = rendered(root)
    assert sorted(files) == [MANAGER, e2e.PRODUCT_TS, VIEWER]
    for path, text in files.items():
        assert (frontend / path).read_text(encoding='utf-8') == text
    assert 'Generated 2 end-to-end tests' in out
    lock = lock_of(root)
    assert lock['e2e'] == {
        'spec': {
            path: digest((root / path).read_bytes())
            for path in ['spec/product.yaml', 'spec/screens/task-card.yaml', 'spec/screens/task-list.yaml']
        },
        'generated': {path: digest(text.encode('utf-8')) for path, text in files.items()},
    }
    # the same specs give the same files
    before = {path: (frontend / path).read_bytes() for path in files}
    generate()
    assert {path: (frontend / path).read_bytes() for path in files} == before
    assert lock_of(root) == lock
    assert 'up to date' in generate('--check')
    assert check_e2e(None) == []


@pytest.mark.django_db
def test_e2e_deletes_the_tests_of_a_removed_scenario(root):
    generate()
    frontend = root / 'frontend'
    # a file of the product in generated/ is not one of the generator
    (frontend / 'e2e' / 'generated' / 'mine.spec.ts').write_text('// mine\n', encoding='utf-8')
    edit_product(root, lambda data: data['scenarios'].pop(1))

    with pytest.raises(CommandError) as error:
        generate('--check')
    assert f'{VIEWER} (of a scenario that no longer exists)' in str(error.value)
    assert 'The specs changed since they were generated: spec/product.yaml.' in str(error.value)
    assert (frontend / VIEWER).is_file()

    out = generate()
    assert f'Deleted {VIEWER}' in out
    assert not (frontend / VIEWER).exists()
    assert (frontend / MANAGER).is_file()
    assert (frontend / 'e2e' / 'generated' / 'mine.spec.ts').is_file()
    assert sorted(lock_of(root)['e2e']['generated']) == [MANAGER, e2e.PRODUCT_TS]
    generate('--check')


@pytest.mark.django_db
def test_check_finds_the_stale_and_the_edited_tests(root):
    generate()
    frontend = root / 'frontend'
    (frontend / MANAGER).write_text('// edited\n', encoding='utf-8')
    with pytest.raises(CommandError) as error:
        generate('--check')
    assert f'The end-to-end tests of {frontend} are stale: {MANAGER}.' in str(error.value)
    assert f'Edited after they were generated: {MANAGER}.' in str(error.value)
    assert 'The specs changed' not in str(error.value)
    # --check writes nothing
    assert (frontend / MANAGER).read_text(encoding='utf-8') == '// edited\n'
    [warning] = check_e2e(None)
    assert warning.id == 'front.W003' and MANAGER in warning.msg

    generate()
    edit_product(root, lambda data: data['scenarios'][0]['steps'][2]['fill'].update(title='Another'))
    with pytest.raises(CommandError, match='spec/product.yaml'):
        generate('--check')
    [warning] = check_e2e(None)
    assert 'The specs changed since they were generated: spec/product.yaml.' in warning.msg


@pytest.mark.django_db
def test_e2e_needs_specs_without_errors(root):
    edit_product(root, lambda data: data['scenarios'][0]['steps'].insert(0, {'submit': {}}))
    out = StringIO()
    with pytest.raises(CommandError, match='The specs have 1 errors'):
        call_command('bazis_front', 'e2e', stdout=out)
    assert 'P022' in out.getvalue()
    assert not (root / 'frontend' / 'e2e' / 'generated').exists()
    assert 'e2e' not in lock_of(root)


@pytest.mark.django_db
def test_the_system_check_skips_specs_with_errors(root):
    # no tests generated yet: nothing to compare
    assert check_e2e(None) == []
    generate()
    (root / 'spec' / 'product.yaml').write_text('spec: [\n', encoding='utf-8')
    # front.W002 reports the issues
    assert check_e2e(None) == []


@pytest.mark.django_db
def test_e2e_needs_a_frontend(tmp_path):
    with override_settings(BASE_DIR=str(tmp_path)), pytest.raises(CommandError, match='init'):
        generate()
