# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 6.1.1 on 2026-10-07 10:30

import bazis.contrib.permit.schemas
import model_clone.mixin
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation time')),
                ('dt_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_dt', models.DateTimeField(auto_now_add=True, verbose_name='Status timestamp')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('report', models.TextField(blank=True, default='', verbose_name='Report')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model, bazis.contrib.permit.schemas.PermitStructMixin),
        ),
        migrations.CreateModel(
            name='TaskStatusyTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now_add=True, verbose_name='Status timestamp')),
                ('extra', models.JSONField(default=dict, verbose_name='Transit extra data')),
            ],
            options={
                'verbose_name': 'Task. Transit fact',
                'verbose_name_plural': 'Tasks. Transit facts',
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
