# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 6.1.1 on 2026-10-07 10:30

import bazis.contrib.statusy.models_abstract
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statusy', '0006_transits_related_through'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=bazis.contrib.statusy.models_abstract.status_default, on_delete=django.db.models.deletion.CASCADE, to='statusy.status', verbose_name='Current status'),
        ),
        migrations.AddField(
            model_name='task',
            name='status_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_author_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskstatusytransit',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_author_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskstatusytransit',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='statusy.status'),
        ),
        migrations.AddField(
            model_name='taskstatusytransit',
            name='statusy_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statusy_transits', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskstatusytransit',
            name='transit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='statusy.transit'),
        ),
    ]
