// Generated by `manage.py bazis_front contract` from contract/contract.json: never edit
// it, export the contract again.

/** The path of the route set of each resource, by its JSON:API type. */
export const ROUTES = {
  "bg.task": "/api/v1/bg/task/",
  "tasks.task": "/api/v1/tasks/task/",
  "uploadable.file_upload": "/api/v1/uploadable/file_upload/",
  "users.user": "/api/v1/users/user/",
} as const;

/** The JSON:API type of a resource. */
export type ResourceType = keyof typeof ROUTES;

/** The resources: model, route set, path, actions and fields (type, relation, filter and order labels). */
export const RESOURCES = {
  "bg.task": {
    actions: {
      action_list: "collection",
      action_retrieve: "item",
    },
    fields: {
      args: {
        filter: "args",
        order: "args",
        type: "object",
      },
      author: {
        filter: "author",
        many: false,
        order: "author",
        relation: "users.user",
      },
      author_updated: {
        filter: "author_updated",
        many: false,
        order: "author_updated",
        relation: "users.user",
      },
      cls_path: {
        filter: "cls_path",
        order: "cls_path",
        type: "string",
      },
      dt_created: {
        filter: "dt_created",
        format: "date-time",
        order: "dt_created",
        type: "string",
      },
      dt_finish: {
        filter: "dt_finish",
        format: "date-time",
        order: "dt_finish",
        type: "string",
      },
      dt_start: {
        filter: "dt_start",
        format: "date-time",
        order: "dt_start",
        type: "string",
      },
      dt_updated: {
        filter: "dt_updated",
        format: "date-time",
        order: "dt_updated",
        type: "string",
      },
      envs: {
        filter: "envs",
        order: "envs",
        type: "object",
      },
      error: {
        filter: "error",
        order: "error",
        type: "string",
      },
      expected: {
        filter: "expected",
        order: "expected",
        type: "object",
      },
      file: {
        filter: "file",
        order: "file",
        type: "string",
      },
      file_params: {
        filter: "file_params",
        order: "file_params",
        type: "object",
      },
      handler: {
        filter: "handler",
        many: false,
        order: "handler",
        relation: "bg.task_handler",
      },
      interrupt: {
        filter: "interrupt",
        order: "interrupt",
        type: "boolean",
      },
      kwargs: {
        filter: "kwargs",
        order: "kwargs",
        type: "object",
      },
      log: {
        filter: "log",
        order: "log",
        type: "string",
      },
      name: {
        filter: "name",
        order: "name",
        type: "string",
      },
      performed: {
        filter: "performed",
        order: "performed",
        type: "object",
      },
      phase: {
        filter: "phase",
        order: "phase",
        type: "string",
      },
      phases_history: {
        filter: "phases_history",
        order: "phases_history",
        type: "object",
      },
      pid: {
        filter: "pid",
        order: "pid",
        type: "string",
      },
      result: {
        filter: "result",
        order: "result",
        type: "object",
      },
      state: {
        filter: "state",
        order: "state",
        type: "string",
      },
      task_cron: {
        filter: "task_cron",
        many: false,
        order: "task_cron",
        relation: "bg.task_cron",
      },
    },
    model: "bg.Task",
    path: "/api/v1/bg/task/",
    route_set: "bazis.contrib.bg.routes.BgRoute",
  },
  "tasks.task": {
    actions: {
      action_create: "create",
      action_delete_relationships: "relationship",
      action_destroy: "delete",
      action_dict_data: "other",
      action_list: "collection",
      action_list_id: "other",
      action_post_relationships: "relationship",
      action_retrieve: "item",
      action_schema_create: "schema",
      action_schema_list: "schema",
      action_schema_retrieve: "schema",
      action_schema_transit: "other",
      action_schema_update: "schema",
      action_transit: "other",
      action_update: "update",
      action_update_relationships: "relationship",
      get_route_filter_fields: "schema",
    },
    fields: {
      assignee: {
        filter: "assignee",
        many: false,
        order: "assignee",
        relation: "users.user",
      },
      attachment: {
        filter: "attachment",
        many: false,
        order: "attachment",
        relation: "uploadable.file_upload",
      },
      dt_created: {
        filter: "dt_created",
        format: "date-time",
        order: "dt_created",
        type: "string",
      },
      dt_updated: {
        filter: "dt_updated",
        format: "date-time",
        order: "dt_updated",
        type: "string",
      },
      report: {
        filter: "report",
        order: "report",
        type: "string",
      },
      status: {
        filter: "status",
        many: false,
        order: "status",
        relation: "statusy.status",
      },
      status_author: {
        filter: "status_author",
        many: false,
        order: "status_author",
        relation: "users.user",
      },
      status_dt: {
        filter: "status_dt",
        format: "date-time",
        order: "status_dt",
        type: "string",
      },
      title: {
        filter: "title",
        order: "title",
        type: "string",
      },
    },
    model: "tasks.Task",
    path: "/api/v1/tasks/task/",
    route_set: "tasks.routes.TaskRouteSet",
  },
  "uploadable.file_upload": {
    actions: {
      action_create: "create",
      action_list: "collection",
      action_retrieve: "item",
    },
    fields: {
      extension: {
        filter: "extension",
        order: "extension",
        type: "string",
      },
      file: {
        filter: "file",
        order: "file",
        type: "string",
      },
      name: {
        filter: "name",
        order: "name",
        type: "string",
      },
      size: {
        type: "integer",
      },
    },
    model: "uploadable.FileUpload",
    path: "/api/v1/uploadable/file_upload/",
    route_set: "tasks.routes.FileRouteSet",
  },
  "users.user": {
    actions: {
      action_create: "create",
      action_delete_relationships: "relationship",
      action_destroy: "delete",
      action_dict_data: "other",
      action_list: "collection",
      action_list_id: "other",
      action_post_relationships: "relationship",
      action_retrieve: "item",
      action_schema_create: "schema",
      action_schema_list: "schema",
      action_schema_retrieve: "schema",
      action_schema_update: "schema",
      action_update: "update",
      action_update_relationships: "relationship",
      get_route_filter_fields: "schema",
    },
    fields: {
      date_joined: {
        filter: "date_joined",
        format: "date-time",
        order: "date_joined",
        type: "string",
      },
      dt_first_login: {
        filter: "dt_first_login",
        format: "date-time",
        order: "dt_first_login",
        type: "string",
      },
      email: {
        filter: "email",
        format: "email",
        order: "email",
        type: "string",
      },
      first_name: {
        filter: "first_name",
        order: "first_name",
        type: "string",
      },
      is_active: {
        filter: "is_active",
        order: "is_active",
        type: "boolean",
      },
      is_staff: {
        filter: "is_staff",
        order: "is_staff",
        type: "boolean",
      },
      is_superuser: {
        filter: "is_superuser",
        order: "is_superuser",
        type: "boolean",
      },
      last_login: {
        filter: "last_login",
        format: "date-time",
        order: "last_login",
        type: "string",
      },
      last_name: {
        filter: "last_name",
        order: "last_name",
        type: "string",
      },
      raw_password: {
        type: "string",
      },
      role_current: {
        filter: "role_current",
        many: false,
        order: "role_current",
        relation: "permit.role",
      },
      roles: {
        filter: "roles",
        many: true,
        order: "roles",
        relation: "permit.role",
      },
      username: {
        filter: "username",
        order: "username",
        type: "string",
      },
    },
    model: "users.User",
    path: "/api/v1/users/user/",
    route_set: "bazis.contrib.users.routes.UserRouteSet",
  },
} as const;

/** The roles of bazis-permit with their effective permissions; empty without it. */
export const ROLES = [
  {
    for_anonymous: false,
    groups: [],
    name: "Guest",
    permissions: [],
    slug: "guest",
  },
  {
    for_anonymous: false,
    groups: [
      "tasks_change",
      "tasks_transit",
      "tasks_view",
    ],
    name: "Manager",
    permissions: [
      "tasks.task.field.change.all.all.report.readonly",
      "tasks.task.item.add.all.all",
      "tasks.task.item.change.all.draft",
      "tasks.task.item.transit.all.draft.start",
      "tasks.task.item.transit.all.in_progress.finish",
      "tasks.task.item.view.all.all",
    ],
    slug: "manager",
  },
  {
    for_anonymous: true,
    groups: [
      "tasks_report_hidden",
      "tasks_view",
    ],
    name: "Viewer",
    permissions: [
      "tasks.task.field.view.all.all.report.disable",
      "tasks.task.item.view.all.all",
    ],
    slug: "viewer",
  },
] as const;

/** The statusy models of bazis-statusy with their initial status, statuses and transits; empty without it. */
export const TRANSITS = {
  "tasks.task": {
    initial: "draft",
    statuses: [
      {
        id: "done",
        name: "Done",
      },
      {
        id: "draft",
        name: "Draft",
      },
      {
        id: "in_progress",
        name: "In progress",
      },
    ],
    transits: [
      {
        dst: "done",
        id: "finish",
        name: "Finish",
        payload: {
          required: true,
          schema: {
            properties: {
              report: {
                title: "Report",
                type: "string",
              },
            },
            required: [
              "report",
            ],
            type: "object",
          },
        },
        src: "in_progress",
      },
      {
        dst: "in_progress",
        id: "start",
        name: "Start",
        payload: null,
        src: "draft",
      },
    ],
  },
} as const;

/** The sections of the capability packages, as in contract.json; null without the package. */
export interface Capabilities {
  readonly async_background: { readonly result_path: string | null } | null;
  readonly async_request: { readonly header: string } | null;
  readonly authing: { readonly auth_url: string | null; readonly actions: readonly { readonly code: string; readonly name: string; readonly method: string; readonly url: string }[]; readonly token_param: string } | null;
  readonly bg: { readonly resource: string | null } | null;
  readonly permit: { readonly roles: typeof ROLES } | null;
  readonly statusy: { readonly models: typeof TRANSITS } | null;
  readonly uploadable: { readonly max_size: number | null; readonly resources: readonly string[] } | null;
  readonly users: { readonly token_url: string; readonly user_resource: string } | null;
  readonly ws: { readonly path: string } | null;
}

export const CAPABILITIES: Capabilities = {
  async_background: {
    result_path: "/api/v1/async_background_response/{task_id}/",
  },
  async_request: {
    header: "X-Async-Background",
  },
  authing: {
    actions: [
      {
        code: "password",
        method: "POST",
        name: "Login/Password",
        url: "/api/v1/authing/password/",
      },
    ],
    auth_url: "/api/v1/authing/auth/",
    token_param: "bazis_auth",
  },
  bg: {
    resource: "bg.task",
  },
  permit: {
    roles: ROLES,
  },
  statusy: {
    models: TRANSITS,
  },
  uploadable: {
    max_size: null,
    resources: [
      "uploadable.file_upload",
    ],
  },
  users: {
    token_url: "/api/openapi-token/",
    user_resource: "users.user",
  },
  ws: {
    path: "/ws",
  },
};
