// Generated by `manage.py bazis_front contract` from contract/contract.json: never edit
// it, export the contract again.

/** The path of the route set of each resource, by its JSON:API type. */
export const ROUTES = {
  "tasks.task": "/api/v1/tasks/task/",
  "users.user": "/api/v1/users/user/",
} as const;

/** The JSON:API type of a resource. */
export type ResourceType = keyof typeof ROUTES;

/** The resources: model, route set, path, actions and fields (type, relation, filter and order labels). */
export const RESOURCES = {
  "tasks.task": {
    actions: {
      action_create: "create",
      action_delete_relationships: "relationship",
      action_destroy: "delete",
      action_dict_data: "other",
      action_list: "collection",
      action_list_id: "other",
      action_post_relationships: "relationship",
      action_retrieve: "item",
      action_schema_create: "schema",
      action_schema_list: "schema",
      action_schema_retrieve: "schema",
      action_schema_transit: "other",
      action_schema_update: "schema",
      action_transit: "other",
      action_update: "update",
      action_update_relationships: "relationship",
      get_route_filter_fields: "schema",
    },
    fields: {
      assignee: {
        filter: "assignee",
        many: false,
        order: "assignee",
        relation: "users.user",
      },
      dt_created: {
        filter: "dt_created",
        format: "date-time",
        order: "dt_created",
        type: "string",
      },
      dt_updated: {
        filter: "dt_updated",
        format: "date-time",
        order: "dt_updated",
        type: "string",
      },
      report: {
        filter: "report",
        order: "report",
        type: "string",
      },
      status: {
        filter: "status",
        many: false,
        order: "status",
        relation: "statusy.status",
      },
      status_author: {
        filter: "status_author",
        many: false,
        order: "status_author",
        relation: "users.user",
      },
      status_dt: {
        filter: "status_dt",
        format: "date-time",
        order: "status_dt",
        type: "string",
      },
      title: {
        filter: "title",
        order: "title",
        type: "string",
      },
    },
    model: "tasks.Task",
    path: "/api/v1/tasks/task/",
    route_set: "tasks.routes.TaskRouteSet",
  },
  "users.user": {
    actions: {
      action_create: "create",
      action_delete_relationships: "relationship",
      action_destroy: "delete",
      action_dict_data: "other",
      action_list: "collection",
      action_list_id: "other",
      action_post_relationships: "relationship",
      action_retrieve: "item",
      action_schema_create: "schema",
      action_schema_list: "schema",
      action_schema_retrieve: "schema",
      action_schema_update: "schema",
      action_update: "update",
      action_update_relationships: "relationship",
      get_route_filter_fields: "schema",
    },
    fields: {
      date_joined: {
        filter: "date_joined",
        format: "date-time",
        order: "date_joined",
        type: "string",
      },
      dt_first_login: {
        filter: "dt_first_login",
        format: "date-time",
        order: "dt_first_login",
        type: "string",
      },
      email: {
        filter: "email",
        format: "email",
        order: "email",
        type: "string",
      },
      first_name: {
        filter: "first_name",
        order: "first_name",
        type: "string",
      },
      is_active: {
        filter: "is_active",
        order: "is_active",
        type: "boolean",
      },
      is_staff: {
        filter: "is_staff",
        order: "is_staff",
        type: "boolean",
      },
      is_superuser: {
        filter: "is_superuser",
        order: "is_superuser",
        type: "boolean",
      },
      last_login: {
        filter: "last_login",
        format: "date-time",
        order: "last_login",
        type: "string",
      },
      last_name: {
        filter: "last_name",
        order: "last_name",
        type: "string",
      },
      raw_password: {
        type: "string",
      },
      role_current: {
        filter: "role_current",
        many: false,
        order: "role_current",
        relation: "permit.role",
      },
      roles: {
        filter: "roles",
        many: true,
        order: "roles",
        relation: "permit.role",
      },
      username: {
        filter: "username",
        order: "username",
        type: "string",
      },
    },
    model: "users.User",
    path: "/api/v1/users/user/",
    route_set: "bazis.contrib.users.routes.UserRouteSet",
  },
} as const;

/** The roles of bazis-permit with their effective permissions; empty without it. */
export const ROLES = [
  {
    for_anonymous: false,
    groups: [],
    name: "Guest",
    permissions: [],
    slug: "guest",
  },
  {
    for_anonymous: false,
    groups: [
      "tasks_change",
      "tasks_transit",
      "tasks_view",
    ],
    name: "Manager",
    permissions: [
      "tasks.task.field.view.all.all.report.enable",
      "tasks.task.item.add.all.all",
      "tasks.task.item.change.all.draft",
      "tasks.task.item.transit.all.draft.start",
      "tasks.task.item.transit.all.in_progress.finish",
      "tasks.task.item.view.all.all",
    ],
    slug: "manager",
  },
  {
    for_anonymous: true,
    groups: [
      "tasks_view",
    ],
    name: "Viewer",
    permissions: [
      "tasks.task.field.view.all.all.report.enable",
      "tasks.task.item.view.all.all",
    ],
    slug: "viewer",
  },
] as const;

/** The statusy models of bazis-statusy with their initial status, statuses and transits; empty without it. */
export const TRANSITS = {
  "tasks.task": {
    initial: "draft",
    statuses: [
      {
        id: "done",
        name: "Done",
      },
      {
        id: "draft",
        name: "Draft",
      },
      {
        id: "in_progress",
        name: "In progress",
      },
    ],
    transits: [
      {
        dst: "done",
        id: "finish",
        name: "Finish",
        payload: {
          required: true,
          schema: {
            properties: {
              report: {
                title: "Report",
                type: "string",
              },
            },
            required: [
              "report",
            ],
            type: "object",
          },
        },
        src: "in_progress",
      },
      {
        dst: "in_progress",
        id: "start",
        name: "Start",
        payload: null,
        src: "draft",
      },
    ],
  },
} as const;

/** The sections of the capability packages, as in contract.json; null without the package. */
export interface Capabilities {
  readonly permit: { readonly roles: typeof ROLES } | null;
  readonly statusy: { readonly models: typeof TRANSITS } | null;
  readonly users: { readonly token_url: string; readonly user_resource: string } | null;
}

export const CAPABILITIES: Capabilities = {
  permit: {
    roles: ROLES,
  },
  statusy: {
    models: TRANSITS,
  },
  users: {
    token_url: "/api/openapi-token/",
    user_resource: "users.user",
  },
};
