// Generated by `manage.py bazis_front design` from spec/design/: never edit it, change the
// specs and generate it again.

/** The tone of a status badge (`statuses` of spec/design/theme.yaml). */
export type Tone = 'neutral' | 'primary' | 'info' | 'success' | 'warning' | 'danger';

/** The design of the frontend: the preset of spec/design/theme.yaml with its options. */
export interface Theme {
  /** workspace: a working application; portal: a public shell. */
  readonly preset: 'workspace' | 'portal';
  readonly navigation: 'sidebar' | 'topbar';
  readonly density: 'comfortable' | 'compact';
  readonly composition: {
    /** A list as a table or a grid of cards. */
    readonly list: 'table' | 'cards';
    /** split: the list and the card side by side on a wide screen; pages: the card replaces the list. */
    readonly list_card: 'split' | 'pages';
    /** Forms in a dialog, or in place of the content of the screen. */
    readonly forms: 'dialog' | 'page';
  };
  /** The tone of the badge of a status by its id; neutral for another. */
  readonly statuses: Readonly<Record<string, Tone>>;
  /** Whether tokens.json has the values of a dark mode (the group `dark`). */
  readonly dark: boolean;
}

/** The design of spec/design/theme.yaml, with the defaults of its preset. */
export const THEME: Theme = {
  composition: {
    forms: "dialog",
    list: "table",
    list_card: "split",
  },
  dark: true,
  density: "comfortable",
  navigation: "sidebar",
  preset: "workspace",
  statuses: {
    done: "success",
    draft: "neutral",
    in_progress: "info",
  },
};
