// Copyright 2026 EcoFuture Technology Services LLC and contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Type-level tests: checked by `tsc` (npm run typecheck), never run. The types come from
// the OpenAPI of the core sample (test/fixtures, regenerated by `npm run fixture`).

import { can, createClient, Filter, nextPage, pagination } from '../src/index.js';
import type { RouteSetPath } from '../src/index.js';
import type { paths } from './fixtures/schema.js';

const api = createClient<paths>({ baseUrl: 'https://api.test' });
const PARENT = '/api/v1/entity/parent_entity/';
// keeps the checked values used
export const seen: unknown[] = [];
const CHILD = '/api/v1/entity/child_entity/';

export const routeSets: RouteSetPath<paths>[] = [PARENT, CHILD];
// @ts-expect-error an item path is not a route set
export const notRouteSet: RouteSetPath<paths> = '/api/v1/entity/parent_entity/{item_id}/';

export async function listTyped(): Promise<void> {
  const page = await api.list(PARENT, {
    filter: Filter.and(Filter.where('is_active', true), Filter.where('price__gte', 10)),
    search: 'apple',
    sort: ['-dt_created'],
    page: { limit: 20, offset: 0 },
    fields: { 'entity.parent_entity': ['name', 'price'] },
    meta: ['pagination'],
  });
  const first = page.data[0];
  if (first) {
    const name: string = first.attributes.name;
    // @ts-expect-error an unknown attribute
    seen.push(first.attributes.no_such_field);
    // @ts-expect-error the name is a string
    const wrong: number = first.attributes.name;
    seen.push(name, wrong);
  }
  seen.push(nextPage(page));
  seen.push(pagination(page));

  // @ts-expect-error an unknown path
  await api.list('/api/v1/entity/no_such_entity/');
  // @ts-expect-error a list is called on the path of the route set, not of an item
  await api.list('/api/v1/entity/parent_entity/{item_id}/');
  // @ts-expect-error list does not accept include
  await api.list(PARENT, { include: ['child_entities'] });
  // @ts-expect-error a list has sparse fieldsets only for its own type
  await api.list(PARENT, { fields: { 'entity.child_entity': ['child_name'] } });
  // @ts-expect-error an unknown meta field
  await api.list(PARENT, { meta: ['no_such_meta'] });
  // @ts-expect-error the filter is built with Filter, not written as a string
  await api.list(PARENT, { filter: 'name=apple' });
}

export async function itemTyped(id: string): Promise<void> {
  const item = await api.retrieve(PARENT, id, {
    include: ['child_entities'],
    fields: { 'entity.parent_entity': ['name'], 'entity.child_entity': ['child_name'] },
  });
  const name: string = item.data.attributes.name;
  seen.push(name);

  const created = await api.create(
    PARENT,
    { data: { type: 'entity.parent_entity', attributes: { name: 'apple' }, relationships: {} } },
    { include: ['child_entities'] },
  );
  seen.push(created.data.id);

  await api.create(PARENT, {
    // @ts-expect-error a required attribute is missing
    data: { type: 'entity.parent_entity', attributes: { price: 10 }, relationships: {} },
  });
  await api.create(PARENT, {
    data: {
      type: 'entity.parent_entity',
      // @ts-expect-error an unknown attribute
      attributes: { name: 'apple', no_such_field: 1 },
      relationships: {},
    },
  });
  await api.create(PARENT, {
    data: {
      type: 'entity.parent_entity',
      // @ts-expect-error a value outside the enum
      attributes: { name: 'apple', state: 'no_such_state' },
      relationships: {},
    },
  });

  await api.update(PARENT, id, {
    data: { id, type: 'entity.parent_entity', attributes: { is_active: false }, relationships: {} },
  });
  await api.destroy(PARENT, id);
  // @ts-expect-error retrieve needs an id
  await api.retrieve(PARENT);
}

export async function endpointsTyped(id: string): Promise<void> {
  await api.relationship(PARENT, id, 'child_entities', 'add', [
    { type: 'entity.child_entity', id: 'c1' },
  ]);
  await api.relationship(PARENT, id, 'extended_entity', 'replace', null);
  // @ts-expect-error an unknown relationship operation
  await api.relationship(PARENT, id, 'child_entities', 'set', null);

  const listSchema: Record<string, unknown> = await api.schema(PARENT, 'list');
  const updateSchema: Record<string, unknown> = await api.schema(PARENT, 'update', id);
  // @ts-expect-error the schema of an update is of an item
  await api.schema(PARENT, 'update');
  // @ts-expect-error the route sets of the sample are not statusy
  await api.schema(PARENT, 'transit', id);
  seen.push(listSchema, updateSchema);

  const filterFields = await api.filterFields(CHILD);
  seen.push(filterFields.fields);

  // @ts-expect-error the route sets of the sample are not statusy
  await api.transit(PARENT, id, 'to_done');
}

export async function permitTyped(id: string): Promise<void> {
  const page = await api.list(PARENT, { meta: ['pagination'] });
  // @ts-expect-error the meta of a route set without bazis-permit has no permission fields
  seen.push(can(page.meta, 'change', id));
  seen.push(can({ crud_actions: ['view', 'change'] }, 'view'));
  // @ts-expect-error not an access action
  seen.push(can({ crud_actions: [] }, 'edit'));
  // @ts-expect-error a list meta checks an item by its id only for change and delete
  seen.push(can({ for_change: [] }, 'view', id));
}
