# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
The end-to-end tests of the scenarios of product.yaml (`bazis_front e2e`): a Playwright test
per scenario in `frontend/e2e/generated/<scenario>.spec.ts`, and `product.ts` there, the
part of the specs that the helpers of the frontend (`e2e/bazis/`, the asset `playwright`)
read at run time: the test users of the roles and the routes of the screens.

The steps are those of the walk of `scenarios.py`, the one that `bazis_front check`
checks; each becomes calls of the helpers, which act through the `data-bz` marks of the
screens. The text depends on the specs only: `--check` and `front.W003` render it again and
compare it byte for byte, without Node. The lock records the hashes of the specs the tests
were generated from and their own (`e2e`): the files of a scenario that was removed are
deleted by the next generation.
"""

import json
from pathlib import Path

from ..contract.typescript import constant
from ..vendor import lock as frontend_lock
from .scenarios import Step
from .validate import SPEC_DIR, Specs


GENERATED_DIR = 'e2e/generated'
PRODUCT_TS = f'{GENERATED_DIR}/product.ts'

#: the asset of the helpers that the generated tests import, and its directory
HELPERS = 'playwright'
HELPERS_DIR = 'e2e/bazis'

#: the keys of an `expect` step, in the order of their checks, with their helper
EXPECT = (
    ('screen', 'expectScreen'),
    ('status', 'expectStatus'),
    ('state', 'expectState'),
    ('action_absent', 'expectActionAbsent'),
    ('field_readonly', 'expectFieldReadonly'),
    ('rows', 'expectRows'),
    ('error', 'expectError'),
)


def header(source: str) -> str:
    return (
        f'// Generated by `manage.py bazis_front e2e` from {source}:\n'
        '// never edit it, change the specs and generate it again.\n'
    )


def string(value: str) -> str:
    """
    A TypeScript string literal in single quotes.
    """
    inner = json.dumps(value, ensure_ascii=False)[1:-1].replace('\\"', '"').replace("'", "\\'")
    return f"'{inner}'"


def literal(value) -> str:
    """
    The TypeScript literal of a scalar of the specs, or of an object of them (the values of
    the fields, whose names are identifiers), on one line.
    """
    if isinstance(value, dict):
        return '{ ' + ', '.join(f'{key}: {literal(item)}' for key, item in value.items()) + ' }'
    if isinstance(value, str):
        return string(value)
    return json.dumps(value)


def flow(value) -> str:
    """
    A value of a step as YAML in flow style, for the title of its `test.step`.
    """
    if isinstance(value, dict):
        return '{' + ', '.join(f'{key}: {flow(item)}' for key, item in value.items()) + '}'
    if isinstance(value, str):
        return value or "''"
    return json.dumps(value)


def calls(step: Step) -> list[str]:
    """
    The calls of the helpers that run a step.
    """
    name, value = step.name, step.value
    result = ["app.action('edit')"] if step.edit else []
    if name == 'open':
        result.append(f'app.open({string(value)})')
    elif name == 'open_item':
        result.append(f'app.openItem({{ where: {literal(value["where"])} }})')
    elif name == 'action':
        result.append(f'app.action({string(value)})')
    elif name == 'fill':
        result.append(f'app.fill({literal(value)})')
    elif name == 'upload':
        result.append(f'app.upload({string(value["field"])}, {string(value["file"])})')
    elif name == 'submit':
        result.append('app.submit()')
    elif name == 'transit':
        transit = {'id': value} if isinstance(value, str) else value
        payload = f', {literal(transit["payload"])}' if 'payload' in transit else ''
        result.append(f'app.transit({string(transit["id"])}{payload})')
    elif name == 'expect':
        result += [f'app.{helper}({literal(value[key])})' for key, helper in EXPECT if key in value]
    else:
        raise ValueError(f'unknown step {name}')
    if step.then is not None:
        result.append(f'app.expectScreen({string(step.then)})')
    return result


def render_scenario(scenario: dict, steps: list[Step]) -> str:
    lines = [
        header(f'the scenario `{scenario["id"]}` of {SPEC_DIR}/product.yaml'),
        "import { test } from '@playwright/test';",
        '',
        "import { loginAs } from '../bazis';",
        '',
        "import { PRODUCT } from './product';",
        '',
        f'test({string(scenario["id"])}, async ({{ page }}) => {{',
        f'  const app = await loginAs(page, PRODUCT, {string(scenario["role"])});',
    ]
    for step in steps:
        title = step.name if step.value == {} else f'{step.name}: {flow(step.value)}'
        lines.append(f'  await test.step({string(title)}, async () => {{')
        lines += [f'    await {call};' for call in calls(step)]
        lines.append('  });')
    lines.append('});')
    return '\n'.join(lines) + '\n'


def render_product(specs: Specs) -> str:
    roles = {
        role['id']: {'username': role.get('test_user', {}).get('username')}
        for role in specs.product.get('roles', [])
    }
    screens = {screen_id: {'route': screen['route']} for screen_id, screen in specs.screens.items()}
    return '\n'.join([
        header(f'{SPEC_DIR}/'),
        constant(
            f'What the helpers of e2e/bazis/ read of the specs: the user that a test logs in as '
            f'for each role of {SPEC_DIR}/product.yaml (`test_user`, null without one), and the '
            f'route of each screen of {SPEC_DIR}/screens/.',
            'PRODUCT',
            {'roles': roles, 'screens': screens},
        ),
    ])


def render(specs: Specs) -> dict[str, str]:
    """
    The generated files by their path in the frontend, from specs without errors.
    """
    files = {PRODUCT_TS: render_product(specs)}
    for scenario in specs.product.get('scenarios', []):
        path = f'{GENERATED_DIR}/{scenario["id"]}.spec.ts'
        files[path] = render_scenario(scenario, specs.scenarios[scenario['id']])
    return dict(sorted(files.items()))


def spec_hashes(root: Path) -> dict[str, str]:
    """
    The hashes of the specs that the tests are generated from, by their path in the product
    root: product.yaml and the screens.
    """
    spec = root / SPEC_DIR
    paths = [spec / 'product.yaml', *sorted((spec / 'screens').glob('*.yaml'))]
    return {
        it.relative_to(root).as_posix(): frontend_lock.digest(it.read_bytes())
        for it in paths if it.is_file()
    }


def generated_path(frontend: Path, path: str) -> bool:
    """
    Whether a path of the lock is a file of `e2e/generated/` of the frontend: the generator
    never deletes or reports any other, whatever the lock lists.
    """
    return (frontend / path).resolve().is_relative_to((frontend / GENERATED_DIR).resolve())


def removed_files(frontend: Path, lock: dict, rendered: dict[str, str]) -> list[str]:
    """
    The generated files of the lock that the specs no longer generate and that still exist.
    """
    return sorted(
        path for path in lock.get('e2e', {}).get('generated', {})
        if path not in rendered and generated_path(frontend, path) and (frontend / path).is_file()
    )


def stale(root: Path, frontend: Path, lock: dict, rendered: dict[str, str]) -> list[str]:
    """
    Why the generated tests of the frontend differ from those of the specs, one message for
    each; empty when they are current. The files are compared byte for byte; those of the
    lock that the specs no longer generate are stale while they exist.
    """
    recorded = lock.get('e2e', {})
    generated = recorded.get('generated', {})
    names = [
        path for path, text in rendered.items()
        if not (frontend / path).is_file() or (frontend / path).read_bytes() != text.encode('utf-8')
    ]
    removed = removed_files(frontend, lock, rendered)
    if not names and not removed:
        return []
    problems = [
        f'The end-to-end tests of {frontend} are stale: '
        + ', '.join(
            [*names, *(f'{it} (of a scenario that no longer exists)' for it in removed)]
        )
        + '.'
    ]
    previous = recorded.get('spec', {})
    current = spec_hashes(root)
    if changed := sorted(it for it in {*previous, *current} if previous.get(it) != current.get(it)):
        problems.append(f'The specs changed since they were generated: {", ".join(changed)}.')
    edited = [
        it for it in names
        if it in generated and (frontend / it).is_file()
        and frontend_lock.digest((frontend / it).read_bytes()) != generated[it]
    ]
    if edited:
        problems.append(f'Edited after they were generated: {", ".join(edited)}.')
    return problems


def write(root: Path, frontend: Path, lock: dict, rendered: dict[str, str]) -> list[str]:
    """
    Writes the generated tests, deletes those of the lock that the specs no longer generate
    and records the hashes of the specs and of the files in the lock. Returns the deleted
    paths.
    """
    removed = removed_files(frontend, lock, rendered)
    for path, text in rendered.items():
        target = frontend / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding='utf-8', newline='\n')
    for path in removed:
        (frontend / path).unlink()
    lock['e2e'] = {
        'spec': spec_hashes(root),
        'generated': {
            path: frontend_lock.digest(text.encode('utf-8')) for path, text in rendered.items()
        },
    }
    frontend_lock.write(frontend, lock)
    return removed
