# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
The theme of the frontend (`bazis_front design`): spec/design/theme.yaml and tokens.json
compiled into `frontend/src/bazis/generated/`:

- `theme.css`, imported by `src/index.css`: the tokens as CSS variables of `:root` and of
  the dark mode (the class `dark` of `<html>`, or the system's unless it has the class
  `light`), the spacing of the density, the Tailwind theme over them (`bg-primary`,
  `bg-success-soft text-success-ink`, `font-display`, `rounded-lg`) and the base styles of
  the preset;
- `theme.ts`, `THEME`: the options of the preset (navigation, density, composition, the
  tones of the statuses, whether there is a dark mode) that the components read.

Without spec/design/ the theme is that of the starter of the preset `workspace`. The text
depends on the specs only: `--check` and `front.W005` render it again and compare it byte
for byte, without Node and the database; the lock records the hashes of the specs and of
the files (`design`).
"""

from pathlib import Path

from ..contract.typescript import literal
from ..vendor import lock as frontend_lock
from . import design
from .validate import SPEC_DIR, Specs


GENERATED_DIR = 'src/bazis/generated'
THEME_CSS = f'{GENERATED_DIR}/theme.css'
THEME_TS = f'{GENERATED_DIR}/theme.ts'

#: the files of the design in the product root
DESIGN_FILES = (f'{SPEC_DIR}/design/theme.yaml', f'{SPEC_DIR}/design/tokens.json')

#: the options of each preset, when theme.yaml does not give them
PRESETS = {
    'workspace': {
        'navigation': 'sidebar',
        'density': 'comfortable',
        'composition': {'list': 'table', 'list_card': 'split', 'forms': 'dialog'},
    },
    'portal': {
        'navigation': 'topbar',
        'density': 'comfortable',
        'composition': {'list': 'cards', 'list_card': 'pages', 'forms': 'page'},
    },
}

#: the spacing of each density: the padding of the page, the gap between the sections of a
#: screen, the padding of the cards, of the cells of the tables, the gap between the fields
DENSITY = {
    'comfortable': {
        '--space-page-x': '2rem',
        '--space-page-y': '1.75rem',
        '--space-section': '1.5rem',
        '--space-card': '1.5rem',
        '--space-cell-x': '1rem',
        '--space-cell-y': '0.75rem',
        '--space-field': '1.25rem',
    },
    'compact': {
        '--space-page-x': '1.25rem',
        '--space-page-y': '1.25rem',
        '--space-section': '1rem',
        '--space-card': '1rem',
        '--space-cell-x': '0.75rem',
        '--space-cell-y': '0.4rem',
        '--space-field': '0.875rem',
    },
}

#: the base styles of each preset, after those of both
PRESET_BASE = {
    'workspace': [],
    'portal': [
        # larger type and more air: every rem grows
        'html {\n    font-size: 106.25%;\n  }',
        'h1,\n  h2,\n  h3 {\n    letter-spacing: -0.02em;\n  }',
    ],
}

CSS_HEADER = (
    '/*\n'
    '  Generated by `manage.py bazis_front design` from spec/design/: never edit it, change the\n'
    '  specs and generate it again. Imported by src/index.css.\n'
    '*/\n'
)

TS_HEADER = (
    '// Generated by `manage.py bazis_front design` from spec/design/: never edit it, change the\n'
    '// specs and generate it again.\n'
)

TS_TYPES = """\
/** The tone of a status badge (`statuses` of spec/design/theme.yaml). */
export type Tone = 'neutral' | 'primary' | 'info' | 'success' | 'warning' | 'danger';

/** The design of the frontend: the preset of spec/design/theme.yaml with its options. */
export interface Theme {
  /** workspace: a working application; portal: a public shell. */
  readonly preset: 'workspace' | 'portal';
  readonly navigation: 'sidebar' | 'topbar';
  readonly density: 'comfortable' | 'compact';
  readonly composition: {
    /** A list as a table or a grid of cards. */
    readonly list: 'table' | 'cards';
    /** split: the list and the card side by side on a wide screen; pages: the card replaces the list. */
    readonly list_card: 'split' | 'pages';
    /** Forms in a dialog, or in place of the content of the screen. */
    readonly forms: 'dialog' | 'page';
  };
  /** The tone of the badge of a status by its id; neutral for another. */
  readonly statuses: Readonly<Record<string, Tone>>;
  /** Whether tokens.json has the values of a dark mode (the group `dark`). */
  readonly dark: boolean;
}
"""


def options(theme: dict | None) -> dict:
    """
    The options of theme.yaml with the defaults of its preset (`workspace` without one).
    """
    theme = theme or {'preset': 'workspace'}
    preset = theme['preset']
    defaults = PRESETS[preset]
    return {
        'preset': preset,
        'navigation': theme.get('navigation', defaults['navigation']),
        'density': theme.get('density', defaults['density']),
        'composition': {**defaults['composition'], **theme.get('composition', {})},
        'statuses': dict(theme.get('statuses', {})),
    }


def block(selector: str, values: dict[str, str], indent: str = '') -> str:
    lines = [f'{indent}{selector} {{']
    lines += [f'{indent}  {name}: {value};' for name, value in values.items()]
    lines.append(f'{indent}}}')
    return '\n'.join(lines)


def theme_mapping(defined: dict) -> dict[str, str]:
    """
    The Tailwind theme over the variables: a color utility for every color token and tone,
    the fonts and the radii.
    """
    colors = sorted(
        {design.variable(name) for name, (_, token) in defined.items() if token['$type'] == 'color'}
        | {design.variable(name) for name, (kind, _, _) in design.DEFAULTS.items() if kind == 'color'}
    )
    mapping = {
        '--font-sans': 'var(--font-body)',
        '--font-display': 'var(--font-heading)',
        '--radius-sm': 'calc(var(--radius) - 4px)',
        '--radius-md': 'calc(var(--radius) - 2px)',
        '--radius-lg': 'var(--radius)',
        '--radius-xl': 'calc(var(--radius) + 4px)',
        '--radius-2xl': 'calc(var(--radius) + 8px)',
    }
    mapping.update({f'--color-{name[2:]}': f'var({name})' for name in colors})
    mapping.update({f'--color-{tone}': f'var({source})' for tone, source in design.TONES.items() if f'--color-{tone}' not in mapping})
    mapping.update({f'--color-{name[2:]}': value for name, value in design.DERIVED.items()})
    return mapping


def render_css(settings: dict, defined: dict) -> str:
    light = {k: v for k, v in design.variables(defined).items() if k not in design.DERIVED}
    dark = design.has_dark(defined)
    night = {
        k: v for k, v in design.variables(defined, dark=True).items()
        if k not in design.DERIVED and light.get(k) != v
    } if dark else {}
    parts = [
        CSS_HEADER,
        f'/* The preset `{settings["preset"]}`, density {settings["density"]}. */',
        '',
        '@custom-variant dark (&:is(.dark *));',
        '',
        block(':root', {**light, **DENSITY[settings['density']]}),
        '',
    ]
    if dark:
        parts += [
            '/* The dark mode: the class `dark` of <html>, or the system\'s unless <html> has the class `light`. */',
            block('.dark', night),
            '',
            '@media (prefers-color-scheme: dark) {',
            block(':root:not(.light)', night, '  '),
            '}',
            '',
        ]
    parts += [
        block('@theme inline', theme_mapping(defined)),
        '',
        '@layer base {',
        '  * {\n    @apply border-border outline-ring/50;\n  }',
        '  html {\n    color-scheme: light;\n  }',
    ]
    if dark:
        parts += [
            '  html.dark {\n    color-scheme: dark;\n  }',
            '  @media (prefers-color-scheme: dark) {\n    html:not(.light) {\n      color-scheme: dark;\n    }\n  }',
        ]
    parts += [
        '  body {\n    @apply bg-background font-sans text-foreground antialiased;\n  }',
        '  h1,\n  h2,\n  h3 {\n    font-family: var(--font-heading);\n  }',
        '  ::selection {\n    background-color: color-mix(in srgb, var(--primary) 22%, transparent);\n  }',
        *(f'  {it}' for it in PRESET_BASE[settings['preset']]),
        '}',
    ]
    return '\n'.join(parts) + '\n'


def render_ts(settings: dict, dark: bool) -> str:
    value = {**settings, 'dark': dark}
    return '\n'.join([
        TS_HEADER,
        TS_TYPES,
        '/** The design of spec/design/theme.yaml, with the defaults of its preset. */',
        f'export const THEME: Theme = {literal(value)};',
        '',
    ])


def render(specs: Specs) -> dict[str, str]:
    """
    The generated files by their path in the frontend, from specs whose design has no errors.
    """
    settings = options(specs.theme)
    defined = design.effective_tokens(settings['preset'], specs.tokens)
    return {
        THEME_CSS: render_css(settings, defined),
        THEME_TS: render_ts(settings, design.has_dark(defined)),
    }


def spec_hashes(root: Path) -> dict[str, str]:
    return {
        path: frontend_lock.digest((root / path).read_bytes())
        for path in DESIGN_FILES if (root / path).is_file()
    }


def stale(root: Path, frontend: Path, lock: dict, rendered: dict[str, str]) -> list[str]:
    """
    Why the theme of the frontend differs from that of the specs, one message for each;
    empty when it is current. The files are compared byte for byte.
    """
    recorded = lock.get('design', {})
    names = [
        path for path, text in rendered.items()
        if not (frontend / path).is_file() or (frontend / path).read_bytes() != text.encode('utf-8')
    ]
    if not names:
        return []
    problems = [f'The theme of {frontend} is stale: {", ".join(names)}.']
    previous, current = recorded.get('spec', {}), spec_hashes(root)
    if changed := sorted(it for it in {*previous, *current} if previous.get(it) != current.get(it)):
        problems.append(f'The design changed since it was generated: {", ".join(changed)}.')
    generated = recorded.get('generated', {})
    edited = [
        it for it in names
        if it in generated and (frontend / it).is_file()
        and frontend_lock.digest((frontend / it).read_bytes()) != generated[it]
    ]
    if edited:
        problems.append(f'Edited after it was generated: {", ".join(edited)}.')
    return problems


def write(root: Path, frontend: Path, lock: dict, rendered: dict[str, str]) -> None:
    """
    Writes the theme and records the hashes of the design and of the files in the lock.
    """
    for path, text in rendered.items():
        target = frontend / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding='utf-8', newline='\n')
    lock['design'] = {
        'spec': spec_hashes(root),
        'generated': {path: frontend_lock.digest(text.encode('utf-8')) for path, text in rendered.items()},
    }
    frontend_lock.write(frontend, lock)
