# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
`contract.ts`: the content of contract.json as typed TypeScript constants (`as const`), so
that the frontend reads the resources, roles, transits and capabilities of the backend with
their literal types. The same contract gives the same text.

`CAPABILITIES` has every capability known to bazis-front, `null` when the product does not
install it, with the type of its section: the code of the frontend compiles with and
without each package and checks for it at run time.
"""

import json
import re
from dataclasses import dataclass


HEADER = (
    '// Generated by `manage.py bazis_front contract` from contract/contract.json: never edit\n'
    '// it, export the contract again.\n'
)

IDENTIFIER = re.compile(r'[A-Za-z_$][A-Za-z0-9_$]*')

#: the TypeScript type of the section of each capability (`capabilities.CAPABILITIES`)
SECTION_TYPES = {
    'authing': (
        '{ readonly auth_url: string | null; readonly actions: readonly '
        '{ readonly code: string; readonly name: string; readonly method: string; readonly url: string }[]; '
        'readonly token_param: string }'
    ),
    'permit': '{ readonly roles: typeof ROLES }',
    'statusy': '{ readonly models: typeof TRANSITS }',
    'uploadable': '{ readonly max_size: number | null; readonly resources: readonly string[] }',
    'users': '{ readonly token_url: string; readonly user_resource: string }',
}


@dataclass(frozen=True)
class Constant:
    """
    A reference to another constant of the file.
    """

    name: str


def literal(value, depth: int = 0) -> str:
    """
    The TypeScript literal of a JSON value, with sorted keys.
    """
    if isinstance(value, Constant):
        return value.name
    indent, inner = '  ' * depth, '  ' * (depth + 1)
    if isinstance(value, dict):
        if not value:
            return '{}'
        items = (
            f'{inner}{key if IDENTIFIER.fullmatch(key) else json.dumps(key, ensure_ascii=False)}: '
            f'{literal(item, depth + 1)},'
            for key, item in sorted(value.items())
        )
        return '{\n' + '\n'.join(items) + f'\n{indent}}}'
    if isinstance(value, list):
        if not value:
            return '[]'
        items = (f'{inner}{literal(item, depth + 1)},' for item in value)
        return '[\n' + '\n'.join(items) + f'\n{indent}]'
    return json.dumps(value, ensure_ascii=False)


def constant(doc: str, name: str, value) -> str:
    return f'/** {doc} */\nexport const {name} = {literal(value)} as const;\n'


def render(contract: dict) -> str:
    """
    The text of `contract.ts` for the content of contract.json.
    """
    resources = contract['project']['resources']
    capabilities = contract['capabilities']
    if unknown := sorted(set(capabilities) - set(SECTION_TYPES)):
        raise ValueError(f'contract.ts has no type for the capabilities {unknown}')
    roles = capabilities.get('permit', {}).get('roles', [])
    transits = capabilities.get('statusy', {}).get('models', {})
    # the sections of the capabilities refer to the constants of their parts
    parts = {('permit', 'roles'): Constant('ROLES'), ('statusy', 'models'): Constant('TRANSITS')}
    sections = {
        name: {key: parts.get((name, key), value) for key, value in section.items()}
        if (section := capabilities.get(name)) is not None
        else None
        for name in SECTION_TYPES
    }
    capabilities_type = ''.join(
        f'  readonly {name}: {type_} | null;\n' for name, type_ in sorted(SECTION_TYPES.items())
    )
    return '\n'.join([
        HEADER,
        constant(
            'The path of the route set of each resource, by its JSON:API type.',
            'ROUTES',
            {type_: resource['path'] for type_, resource in resources.items()},
        ),
        '/** The JSON:API type of a resource. */\n'
        'export type ResourceType = keyof typeof ROUTES;\n',
        constant(
            'The resources: model, route set, path, actions and fields (type, relation, '
            'filter and order labels).',
            'RESOURCES',
            resources,
        ),
        constant(
            'The roles of bazis-permit with their effective permissions; empty without it.',
            'ROLES',
            roles,
        ),
        constant(
            'The statusy models of bazis-statusy with their initial status, statuses and '
            'transits; empty without it.',
            'TRANSITS',
            transits,
        ),
        '/** The sections of the capability packages, as in contract.json; null without the '
        'package. */\n'
        f'export interface Capabilities {{\n{capabilities_type}}}\n',
        f'export const CAPABILITIES: Capabilities = {literal(sections)};\n',
    ])
