// Copyright 2026 EcoFuture Technology Services LLC and contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// The helpers of the end-to-end tests: the steps of the scenarios of the specs over the
// screens, through their `data-bz` marks only. The tests generated by
// `manage.py bazis_front e2e` (`e2e/generated/`) call them with `PRODUCT` of
// `e2e/generated/product.ts` (the test users and the routes of the specs), and so can the
// tests of the product (`e2e/custom/`). They wait with the auto-waiting of Playwright and on
// the marks of the states, never for a fixed time.

import path from 'node:path';

import { expect, type Locator, type Page } from '@playwright/test';

import { CAPABILITIES } from '@/bazis/generated/contract';

/**
 * The part of the specs that the helpers read, `PRODUCT` of `e2e/generated/product.ts`: the
 * test user of each role of spec/product.yaml (`test_user`, null without one) and the route
 * of each screen of spec/screens/.
 */
export interface Product {
  readonly roles: Readonly<Record<string, { readonly username: string | null }>>;
  readonly screens: Readonly<Record<string, { readonly route: string }>>;
}

/** A role of the specs. */
export type Role<P extends Product> = keyof P['roles'] & string;

/** A screen of the specs. */
export type ScreenId<P extends Product> = keyof P['screens'] & string;

/** The values of fields by name, scalars as in the specs. */
export type Values = Readonly<Record<string, string | number | boolean | null>>;

/** The states that the screens render (`state:<state>`). */
export type State = 'loading' | 'empty' | 'loaded' | 'error' | 'forbidden' | 'not_found' | 'invalid';

/** The selector of the mark `data-bz="<kind>:<id>"`. */
export function bz(kind: string, id: string): string {
  return `[data-bz=${JSON.stringify(`${kind}:${id}`)}]`;
}

/** The marks of a failure: the error states and the errors of the fields. */
const FAILURES = [
  ...['error', 'forbidden', 'not_found', 'invalid'].map((state) => bz('state', state)),
  '[data-bz^="error:"]',
];
const FAILED = FAILURES.join(', ');

/** The attribute that the helpers set on the marks of a failure shown before a step. */
const SEEN = 'data-bz-seen';

/** The marks of a failure shown since the step started. */
const NEW_FAILED = FAILURES.map((it) => `${it}:not([${SEEN}])`).join(', ');

/** The login screen of the template (`LoginForm`). */
const LOGIN_ROUTE = '/login';

/** The files that `upload` takes, `e2e/fixtures/` of the frontend. */
const FIXTURES = path.join(import.meta.dirname, '..', 'fixtures');

/**
 * The pattern of the paths of a route of the specs: `/tasks/:id` is any `/tasks/<id>`, with or
 * without a trailing slash.
 */
export function routePattern(route: string): RegExp {
  const parts = route
    .replace(/\/+$/, '')
    .split('/')
    .map((part) => (part.startsWith(':') ? '[^/]+' : part.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  return new RegExp(`^${parts.join('/')}/?$`);
}

/** A text that is the whole text of an element. */
function exactly(value: string | number | boolean | null): RegExp {
  const text = value === null ? '' : String(value);
  return new RegExp(`^\\s*${text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*$`);
}

/**
 * The application in a page, at a screen of the specs. The steps act on the current screen
 * (set by `open` and `expectScreen`) and on the open form, the `<form>` with
 * `action:submit` (a dialog, the edit of a card, a form screen).
 */
export class App<P extends Product = Product> {
  private current: ScreenId<P> | null = null;

  constructor(
    readonly page: Page,
    readonly product: P,
  ) {}

  /** The current screen, `screen:<id>`. */
  screen(): Locator {
    if (this.current === null) throw new Error('No screen is open: start with `open` or `expectScreen`.');
    return this.page.locator(bz('screen', this.current));
  }

  /** The open form. */
  form(): Locator {
    return this.page.locator(`form:has(${bz('action', 'submit')})`);
  }

  /** Opens a screen by its route (one without the id of an item) and waits for its state. */
  async open(screen: ScreenId<P>): Promise<void> {
    const target = this.product.screens[screen];
    if (target === undefined) throw new Error(`The screen ${screen} is not in the specs.`);
    const { route } = target;
    if (route.includes(':')) {
      throw new Error(`The screen ${screen} shows an item (${route}): reach it with openItem.`);
    }
    await this.page.goto(route);
    await this.expectScreen(screen);
  }

  /** Opens the first row of the list of the current screen whose cells have these texts. */
  async openItem({ where }: { where: Values }): Promise<void> {
    await this.settled();
    let rows = this.screen().locator('[data-bz^="row:"]');
    for (const [name, value] of Object.entries(where)) {
      rows = rows.filter({ has: this.page.locator(bz('cell', name)).filter({ hasText: exactly(value) }) });
    }
    await rows.first().click();
  }

  /** Runs an action of the current screen, `action:<id>`. */
  async action(id: string): Promise<void> {
    await this.screen().locator(bz('action', id)).click();
  }

  /**
   * Fills fields of the open form, `field:<name>`: a text, a number, a date; a select (a
   * choice) by the label of its option; a combobox (the picker of a relationship) by the
   * label of the item, searched in its popup, null by its option that clears the value; a
   * checkbox by true or false.
   */
  async fill(values: Values): Promise<void> {
    const form = this.form();
    for (const [name, value] of Object.entries(values)) {
      const control = form.locator(bz('field', name));
      const kind = await control.evaluate((element) =>
        element.getAttribute('role') === 'combobox'
          ? 'combobox'
          : element instanceof HTMLInputElement
            ? element.type
            : element.tagName.toLowerCase(),
      );
      if (kind === 'checkbox') await control.setChecked(value === true);
      else if (kind === 'select') await control.selectOption(value === null ? { value: '' } : { label: String(value) });
      else if (kind === 'combobox') await this.choose(control, value);
      else await control.fill(value === null ? '' : String(value));
    }
  }

  /**
   * Chooses an item in a combobox: opens its popup (`aria-controls`), searches the label and
   * clicks the option with exactly that text, or the option that clears the value
   * (`data-value=""`); waits until the popup is closed.
   */
  private async choose(control: Locator, value: string | number | boolean | null): Promise<void> {
    await control.click();
    const popup = this.page.locator(`[id=${JSON.stringify((await control.getAttribute('aria-controls')) ?? '')}]`);
    if (value === null) {
      await popup.locator('[role="option"][data-value=""]').click();
    } else {
      await popup.getByRole('combobox').fill(String(value));
      await popup.getByRole('option', { name: exactly(value) }).click();
    }
    await expect(popup).toHaveCount(0);
  }

  /** Sets the file of a field of the open form: a path in `e2e/fixtures/`. */
  async upload(field: string, file: string): Promise<void> {
    await this.form().locator(bz('field', field)).setInputFiles(path.join(FIXTURES, file));
  }

  /**
   * Submits the open form and waits until it is closed (saved) or shows an error of this
   * submit (not one of a previous submit), which the next step expects (`expectError`,
   * `expectState`).
   */
  async submit(): Promise<void> {
    const form = this.form();
    await this.seen(form);
    await form.locator(bz('action', 'submit')).click();
    await this.until(form, form.locator(NEW_FAILED), 'the form is closed or shows an error');
  }

  /**
   * Runs a transit of the item of the current screen, `transit:<id>`, with the values of
   * its payload in its dialog, and waits until it is done (the transit is no longer
   * offered) or shows an error.
   */
  async transit(id: string, payload?: Values): Promise<void> {
    const button = this.screen().locator(bz('transit', id));
    await this.seen(this.page.locator('body'));
    await button.click();
    if (payload !== undefined) {
      await this.fill(payload);
      await this.submit();
    }
    await this.until(button, this.page.locator(NEW_FAILED), `the transit ${id} is done or shows an error`);
  }

  /**
   * The current screen is this one: at its route (another screen may show next to it, such
   * as a list next to its card), with its state rendered.
   */
  async expectScreen(screen: ScreenId<P>): Promise<void> {
    const target = this.product.screens[screen];
    if (target === undefined) throw new Error(`The screen ${screen} is not in the specs.`);
    await expect(this.page.locator(bz('screen', screen))).toBeVisible();
    await expect
      .poll(() => new URL(this.page.url()).pathname, { message: `the route of the screen ${screen} (${target.route})` })
      .toMatch(routePattern(target.route));
    this.current = screen;
    await this.settled();
  }

  /** The item of the current screen has this status, `status:<id>`. */
  async expectStatus(status: string): Promise<void> {
    await expect(this.screen().locator(bz('status', status)).first()).toBeVisible();
  }

  /** The page shows this state, `state:<state>` (a screen kept hidden next to it does not count). */
  async expectState(state: State): Promise<void> {
    await expect(this.page.locator(bz('state', state)).filter({ visible: true }).first()).toBeVisible();
  }

  /** The current screen, once loaded, does not offer this action. */
  async expectActionAbsent(id: string): Promise<void> {
    await this.settled();
    await expect(this.screen().locator(bz('action', id))).toHaveCount(0);
  }

  /**
   * The user may not change the field: read-only (or not there) in the open form; on a card
   * without a form, the card has no edit (`action:edit`), or its edit has the field
   * read-only (the edit is opened and cancelled).
   */
  async expectFieldReadonly(field: string): Promise<void> {
    await this.settled();
    const form = this.form();
    if ((await form.count()) > 0) {
      await this.expectReadonlyIn(form, field);
      return;
    }
    const screen = this.screen();
    const edit = screen.locator(bz('action', 'edit'));
    if ((await edit.count()) === 0) {
      await expect(screen.locator(bz('field', field)).first()).toBeVisible();
      return;
    }
    await edit.click();
    await expect(form).toBeVisible();
    await this.expectReadonlyIn(form, field);
    await form.locator(bz('action', 'cancel')).click();
    await expect(form).toHaveCount(0);
  }

  /**
   * The user may not see the field: the current screen, once loaded, has no `field:<name>`
   * (a card, the open form) and no cell `cell:<name>` (a list).
   */
  async expectFieldAbsent(field: string): Promise<void> {
    await this.settled();
    await expect(this.screen().locator(`${bz('field', field)}, ${bz('cell', field)}`)).toHaveCount(0);
    await expect(this.form().locator(bz('field', field))).toHaveCount(0);
  }

  /** The list of the current screen has this number of rows, `row:<id>`. */
  async expectRows(count: number): Promise<void> {
    await this.settled();
    await expect(this.screen().locator('[data-bz^="row:"]')).toHaveCount(count);
  }

  /** A field shows a validation error, `error:<name>`. */
  async expectError(field: string): Promise<void> {
    await expect(this.page.locator(bz('error', field)).filter({ visible: true }).first()).toBeVisible();
  }

  private async expectReadonlyIn(form: Locator, field: string): Promise<void> {
    const control = form.locator(bz('field', field));
    if ((await control.count()) > 0) await expect(control).not.toBeEditable();
  }

  /** Waits until the current screen has rendered a state and nothing on the page loads. */
  private async settled(): Promise<void> {
    await expect(this.screen().locator('[data-bz^="state:"]').first()).toBeAttached();
    await expect(this.page.locator(bz('state', 'loading'))).toHaveCount(0);
  }

  /**
   * Marks the failures shown in the scope, so that a step waits for its own: those of a
   * previous submit stay on the page until the next one is sent.
   */
  private async seen(scope: Locator): Promise<void> {
    await scope.locator(FAILED).evaluateAll((elements, attribute) => {
      for (const element of elements) element.setAttribute(attribute, '');
    }, SEEN);
  }

  /** Waits until `gone` is no longer on the page or `failed` is. */
  private async until(gone: Locator, failed: Locator, message: string): Promise<void> {
    await expect
      .poll(async () => (await gone.count()) === 0 || (await failed.count()) > 0, { message })
      .toBe(true);
  }
}

/**
 * Opens the application as the test user of the role (`test_user` of spec/product.yaml,
 * the password of the environment variable E2E_PASSWORD) through the login screen. Without
 * bazis-users there is no login: the application is open.
 */
export async function loginAs<P extends Product>(page: Page, product: P, role: Role<P>): Promise<App<P>> {
  const app = new App(page, product);
  if (CAPABILITIES.users === null) return app;
  const user = product.roles[role];
  if (user === undefined) throw new Error(`The role ${role} is not in the specs.`);
  const { username } = user;
  if (username === null) {
    throw new Error(`The role ${role} has no test_user in spec/product.yaml: the test cannot log in.`);
  }
  const password = process.env.E2E_PASSWORD;
  if (!password) throw new Error('Set E2E_PASSWORD, the password of the test users.');
  await page.goto(LOGIN_ROUTE);
  const form = app.form();
  await app.fill({ username, password });
  await form.locator(bz('action', 'submit')).click();
  const failed = form.locator(FAILED);
  await expect(page.locator(bz('action', 'logout')).or(failed).first()).toBeVisible();
  if ((await failed.count()) > 0) {
    throw new Error(`${username} cannot log in: ${await failed.first().innerText()}`);
  }
  return app;
}
